### PR TITLE
Added support for Scandinavian Languages

### LINKED ISSUE #126: Allow toggle for raising errors
Currently, tasks fail silently and are written to a file. It would make it easier to debug if it was possible to toggle the raising of errors.

I can create the PR with a solution if this is something you want.

### PR DESCRIPTION
**Pull request by KennethEnevoldsen**
## Addition
- Added all relevant tasks for Da, No, and Sv I could find. Norwegian includes Norwegian Bokmål and Norwegian Nynorsk. Danish also includes a bitext between Danish and one of its dialects.
- Added a minor fix to the Bitext task

## Task selection:
- Wherever possible I try to keep as streamlined with ScandEval as possible. I.e. if there are cases two versions of the dataset exist, I use the same one as ScandEval.
- I do not include machine-translated datasets (this excludes the QA datasets in ScandEval)
- Where possible I use the test split. If there are no splits I use the train split.
- I do not include non-public datasets such as DaNewsroom

## Potential problems
- Can't get a non-zero performance on the retrieval task. See  #122 (A solution is simply to remove it for the first PR)
- Currently, there is an overweight of sentiment classification tasks.

## Other
- I have added the transform_dataset method. Might be relevant to make that a general method in the AbsTask. In that way, the loading workflow is independent of the transformation workflow (would allow you to e.g. add splits without having to fix the custom transformations of each of the datasets). Currently, it is not implemented in the main function.

Fixes #126

### CODE REVIEW

**Review by Muennighoff — COMMENTED** [review]
Amazing work!

- I like the `dataset_transform`. I think we can leave it like you did for now & maybe we'll make it a generic function later
- We still need to import all tasks in the `__init__.py` files for each task directory I think
- Why did you choose 16 `samples_per_label` for all Classification tasks? @NouamaneTazi @loicmagne  do you remember how we selected the different `samples_per_label` values for CLF tasks? Was it based on how big the dataset is / the number of labels?
- Can you run a few models on the new tasks and share the result files here? I can add a new [leaderboard tab](https://huggingface.co/spaces/mteb/leaderboard) for some of these languages where we have a few datasets. Maybe three new CLF tabs for Danish, Norwegian, Swedish? Or is it more useful if it's just one new CLF tab for "Scandinavia"?
- Do we have results on SweFAQRetrieval from prior work & are we able to reproduce it?

**Comment by Muennighoff** [comment]
1. - 3. Sounds great!
4. Nice let me know when you have the files! Then I will add them to the LB & we can merge this 👍
5. Maybe let's remove this task for now then like you suggested? We can add it later if we manage to fix the bug 👍

**Comment by KennethEnevoldsen** [comment]
Perfect. I have send the results by mail.

I have also removed the task and fixed #126

**Review by Muennighoff — APPROVED** [review]
LGTM; Have added all tasks to the leaderboard: https://huggingface.co/spaces/mteb/leaderboard

Let me know if the leaderboard looks okay to you? & then will merge 👍

**Comment by KennethEnevoldsen** [comment]
The only change I would make is change the name of Bitext from other to Danish (it is Danish + a danish dialect). Otherwise I think it looks good!

**Comment by Muennighoff** [comment]
> The only change I would make is to change the name of Bitext from other to Danish (it is Danish + a Danish dialect). Otherwise, I think it looks good!
> 
> Edit: Actually if you wish I am creating an aggregated site for the Scandinavian subsection [here](https://kennethenevoldsen.github.io/scandinavian-embedding-benchmark/) (still working on it). Feel free to link to it. Plan to also add Finnish, Icelandic and Faroese as well in the future (as well as adding them to MTEB).
> 
> Edit: Oh it seems like ScalaNbClassification is in Swedish instead of Norwegian

Fixed & added the link! If you want to link it in a different way, let me know - You can also edit the `app.py` of the leaderboard directly if you want to.

Also FYI all your scores are in this repository: https://huggingface.co/datasets/mteb/results
I renamed some of them to account for the name change in SweRecClassification.

Merging now 🚀

**Pull request merged**
