### PR TITLE
docs: Add lang family mapping and map to task table

### LINKED ISSUE #1485: Add Language Families
Use something like [Glottolog](https://github.com/glottolog/pyglottolog) to add language family info to each ISO369-3 code. 

Creds to @KennethEnevoldsen for instigating this.

### PR DESCRIPTION
**Pull request by isaac-chung**
Fixes #1485.
- Add language family mapping and creation script
- Add language name and family to task name for each ISO code

Table in paper updated.
image

## Checklist

- [x] Run tests locally to make sure nothing is broken using `make test`. 
- [x] Run the formatter to format the code using `make lint`.

### CODE REVIEW

**Review by KennethEnevoldsen — APPROVED** [review]
Great! only one thing to add:

We should probably do create a language category for programming languages. 

I is "language family" programming a bit too odd? Alternatively we should move them to a separate table.

**Comment by isaac-chung** [comment]
Programming sounds good and the least lift 👍

**Comment by isaac-chung** [comment]
@KennethEnevoldsen do you mean
1. replacing the code row with Language=code, Family=Programming, or
2. expanding the code row into individual programming languages, plus Family=Programming, or
3. remove the code row entirely, or
4. something else?

**Comment by KennethEnevoldsen** [comment]
I was thinking Family=Programming

**Comment by isaac-chung** [comment]
@KennethEnevoldsen sure, updated the paper as well. Updating the mapping more based on edits.

**Comment by KennethEnevoldsen** [comment]
Great - where these just manually curated?

**Comment by isaac-chung** [comment]
Yes. Those were "unclassified" which I found to be odd, so I found the closest fit.

**Pull request merged**
