### PR TITLE
Add BEIR-PL datasets to MTEB

### PR DESCRIPTION
**Pull request by kwojtasi**
Add tasks and updated README for datasets in BEIR-PL (BEIR benchmark in Polish language).

### CODE REVIEW

**Review by Muennighoff — COMMENTED** [review]
Amazing work!

I would standardize the names to all be e.g. `DBPediaPL`.
Currently, it seems there's `HotpotQAPL`, but also `DBPedia-pl` & `ArguAna-PL`.


Do you want to merge this first & then lateron add the missing datasets (CQA, Touche etc.) in a separate PR?

**Comment by kwojtasi** [comment]
I have updated names to `ArguAna-PL`, it seems to be the most readable option, but if you want other names standardization I can change it. 

We can merge it and I will add another PR for all CQADupstack and Touche datasets.

**Review by Muennighoff — APPROVED** [review]
Looks good to me!
Can you run all tasks for at least 1 model and provide the result files here? I will then update the leaderboard to have a tab for BEIR-PL

**Review by Muennighoff — APPROVED** [review]
Looks great, amazing work!
I've added the results in a new leaderboard tab for Polish under Retrieval: https://huggingface.co/spaces/mteb/leaderboard

Feel free to add more models by either sending the result files or adding the results to the model card of the models.

**Pull request merged**
