### PR TITLE
Adding Kurdish Sentiment dataset

### PR DESCRIPTION
**Pull request by asparius**
## Checklist for adding MMTEB dataset

Reason for dataset addition:

Recently collected Kurdish Sentiment from [paper](https://link.springer.com/article/10.1007/s10579-023-09716-6#citeas) and I believe it is the first Kurdish dataset.

- [x] I have tested that the dataset runs with the `mteb` package.
- [x] I have run the following models on the task (adding the results to the pr). These can be run using the `mteb run -m {model_name} -t {task_name}` command.
  - [x] `sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2`
  - [x] `intfloat/multilingual-e5-small`
- [x] I have checked that the performance is neither trivial (both models gain close to perfect scores) nor random (both models gain close to random scores).
- [x] I have considered the size of the dataset and reduced it if it is too big (2048 examples is typically large enough for most tasks)
- [x] Run tests locally to make sure nothing is broken using `make test`. 
- [x] Run the formatter to format the code using `make lint`. 
- [] I have added points for my submission to the [POINTS.md](https://github.com/embeddings-benchmark/mteb/blob/main/docs/mmteb/points.md) file.

### CODE REVIEW

**Review by isaac-chung — APPROVED** [review]
Nicely done! Don't forget to add 2+4 pts for yourself and 2 pts for my review as well.

**Comment by KennethEnevoldsen** [comment]
let us hold off on merging thus until we have #438 merged in

**Comment by isaac-chung** [comment]
Note the changed scoring system format in https://github.com/embeddings-benchmark/mteb/pull/438. Please update accordingly.

**Comment by KennethEnevoldsen** [comment]
@isaac-chung feel free to just fix the scores in a temporary branch if you want

**Pull request merged**
