### PR TITLE
Fix GritLM Retrieval instructions

### PR DESCRIPTION
**Pull request by Muennighoff**
Issue mentioned in https://github.com/embeddings-benchmark/mteb/pull/976

### CODE REVIEW

**Comment by KennethEnevoldsen** [comment]
Looks good @Muennighoff - I have added a fix for the e5 models as well

**Comment by Muennighoff** [comment]
I think for e5 it was already fine cuz it didn't use the instruction anyways, but also fine to change it like you did 👍

```
        if encode_type == "query":
            sentences = [
                f"Instruction: {instruction}\nQuery: {sentence}"
                for sentence in sentences
            ]
```

**Comment by KennethEnevoldsen** [comment]
sorry I was unclear - changed it for the e5 instruct models only

**Comment by Muennighoff** [comment]
Oh sorry I was unclear - i also meant that for e5 instruct I think it was already fine cuz of the code above, but anyways it's cleaner to explicitly not have an instruction like you changed so all good as is I think! 😁

**Comment by KennethEnevoldsen** [comment]
Oh double misunderstanding there. Well no worries clarity is probably a good thing in this case as you say

**Pull request merged**
