### PR TITLE
(1) Add WebLINX Candidate Elements Reranking Task; (2) move `convert_conv_history_to_query` from `mteb.evaluation.evaluators.RetrievalEvaluator` to `mteb.evaluation.evaluators.utils`

### PR DESCRIPTION
**Pull request by xhluca**
(1) Add WebLINX Candidate Elements Reranking Task; 

(2) move `convert_conv_history_to_query` from `mteb.evaluation.evaluators.RetrievalEvaluator` to `mteb.evaluation.evaluators.utils`

## Checklist for adding MMTEB dataset

Reason for dataset addition:

- [x] I have tested that the dataset runs with the `mteb` package.
- [x] I have run the following models on the task (adding the results to the pr). These can be run using the `mteb -m {model_name} -t {task_name}` command.
  - [x] `sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2`
  - [x] `intfloat/multilingual-e5-small`
- [x] I have checked that the performance is neither trivial (both models gain close to perfect scores) nor random (both models gain close to random scores).
- [x] If the dataset is too big (e.g. >2048 examples), considering using `self.stratified_subsampling() under dataset_transform()`
- [x] I have filled out the metadata object in the dataset file (find documentation on it [here](https://github.com/embeddings-benchmark/mteb/blob/main/docs/adding_a_dataset.md#2-creating-the-metadata-object)).
- [x] Run tests locally to make sure nothing is broken using `make test`. 
- [x] Run the formatter to format the code using `make lint`. 
- [ ] I have added points for my submission to the [points folder](https://github.com/embeddings-benchmark/mteb/blob/main/docs/mmteb/points.md) using the PR number as the filename (e.g. `438.jsonl`).

## Notes

> I have tested that the dataset runs with the mteb package.

To test it, I have used the following code:

```python
from mteb import MTEB


class DummyModel:
    def encode(self, texts, *args, **kwargs):
        return texts


evaluation = MTEB(tasks=["AskUbuntuDupQuestions", "WebLINXCandidatesReranking"])
evaluation.load_tasks_data()
ubuntu = evaluation.tasks[0]
weblinx = evaluation.tasks[1]

# check first query from ubuntu
ubuntu_query = ubuntu.dataset["test"]["query"][0]
print("Ubuntu:", ubuntu_query)

# check first query and postives and negatives from weblinx
weblinx_query = weblinx.dataset["validation"]["query"][0]
weblinx_pos = weblinx.dataset["validation"]["positives"][0][0]
weblinx_neg = weblinx.dataset["validation"]["negatives"][0][0]

print("Weblinx:")
print(weblinx_query)
print("\nWeblinx Positive:")
print(weblinx_pos)
print("\nWeblinx Negative:")
print(weblinx_neg)

print("Splits:")
print(weblinx.dataset.keys())
```

Output:

```

Ubuntu: malformed line * in source list /etc/apt/sources.list ( dist parse )
Weblinx:
User: Hello
Agent: say(speaker="navigator", utterance="Hi")
User: Please open Gmail.
Agent: load(url="https://mail.google.com/mail/u/0/")
Agent: say(speaker="navigator", utterance="Yes, sure")
User: Add a task with the title "Interview."
Agent: say(speaker="navigator", utterance="Okay")
Agent: click(x=1416, y=201, tag="path", attrs={})

Weblinx Positive:
[[tag]] div
[[xpath]] /html/body/div[7]/div[3]/div/div[2]/div[3]/div[1]/div/div[1]/div[1]/div/div[3]/div[3]
[[text]] 
[[bbox]] x=1188 y=184 width=40 height=40
[[attributes]] class='aT5-aOt-I-JX-Jw' data-webtasks-id='112e2f9f-9097-4464' style='background-image: url("https://www.gstatic.com/c...on_assets/tasks_2021_2x.png"); user-select: none;'
[[children]] 

Weblinx Negative:
[[tag]] div
[[xpath]] /html/body/div[7]/div[3]/div/div[1]
[[text]] 
[[bbox]] x=0 y=0 width=1236 height=64
[[attributes]] class='nH w-asV bbg aiw' data-webtasks-id='41956f41-bb96-4ef1'
[[children]] div div
Splits:
dict_keys(['validation', 'test_iid', 'test_cat', 'test_geo', 'test_vis', 'test_web'])
```

> I have run the following models on the task (adding the results to the pr). These can be run using the mteb -m {model_name} -t {task_name} command. 

I ran with:
```bash
mteb -m "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2" -t "WebLINXCandidatesReranking"
mteb -m "intfloat/multilingual-e5-small" -t "WebLINXCandidatesReranking"
```

>  I have checked that the performance is neither trivial (both models gain close to perfect scores) nor random (both models gain close to random scores).

It seems MRR is around 8% to 11%, which seems reasonable that the reciprocal rank is on average 1/12 to 1/10, indicating that the task is fairly hard but far from randomly (considering there is a lot of hundreds of negatives in the task usually).

### CODE REVIEW

**Comment by vaibhavad** [comment]
As discussed, there will be changes in the [RerankingEvaluator.py](https://github.com/embeddings-benchmark/mteb/blob/0ceaff6fa7ed76f5915c66d6b2ac1b46a789f19e/mteb/evaluation/evaluators/RerankingEvaluator.py) to support conversations, similar to those done in #714

**Comment by xhluca** [comment]
> As discussed, there will be changes in the [RerankingEvaluator.py](https://github.com/embeddings-benchmark/mteb/blob/0ceaff6fa7ed76f5915c66d6b2ac1b46a789f19e/mteb/evaluation/evaluators/RerankingEvaluator.py) to support conversations, similar to those done in #714

Thanks. Right now reranking accepts lists of queries unlike retrieval:
```python
        elif isinstance(self.samples[0]["query"], list):
            # In case the query is a list of strings, we get the most similar embedding to any of the queries
            all_query_flattened = [
                q for sample in self.samples for q in sample["query"]
            ]
            all_query_embs = self._encode_unique_texts(
                all_query_flattened, encode_corpus_func
            )
```

This means it is not compatible with conversations which are lists (i.e. there's no current way to disambiguate a query that is a list of queries and a query that is a list of conversation turns).

**Comment by xhluca** [comment]
@vaibhavad ready for review (for real this time)! I set aside the query part, but i think we could add it in the future if we decide to drop support for query list reranking.

**Review by vaibhavad — APPROVED** [review]
Looks good to me. Feel free to add couple of points under bug fixes, and take the latest changes from main. You should be able to merge after that.

**Comment by xhluca** [comment]
@vaibhavad I've added the points, updated the branch with the new main changes/resolve conflicts, and reran linting. Feel free to merge when the tests pass.

**Pull request merged**
