### PR TITLE
Add descriptive stats to mising tasks and add number of qrels

### PR DESCRIPTION
**Pull request by imenelydiaker**
## Checklist

- [x] Run tests locally to make sure nothing is broken using `make test`. 
- [x] Run the formatter to format the code using `make lint`. 

---

I ran some of the missing tasks, and @dokato is running the rest. Also added in this PR the number of qrels (`num_relevant_docs`) for retrieval datasets (updated 2 tasks for testing).

### CODE REVIEW

**Review by Samoed — APPROVED** [review]
Awesome!

**Comment by imenelydiaker** [comment]
@Samoed can you check the tests? I'm not sure why they're not passing 🤔

**Comment by Samoed** [comment]
I'll fix them in 2h

**Comment by Samoed** [comment]
It seems that it tried to merge this branch with `2.0.0` and applied the test from there. In the `2.0.0` branch, I updated the test to check whether a task has metadata or not.

**Comment by Samoed** [comment]
I think this can be merged now @imenelydiaker

**Comment by imenelydiaker** [comment]
Thanks @Samoed, merging!

**Pull request merged**
