### PR TITLE
Added script for creating contributions and author list

### PR DESCRIPTION
**Pull request by KennethEnevoldsen**
I imagine there are still a few points missing, but this creates the relevant items for the paper related to contributors, points and affil. 

@imenelydiaker replaced the list you created with the one using this script (to have it sorted correctly). I have updated the paper with the latest version and commented the old one out. 

@isaac-chung I can see that you do not have affiliations - just wanted to make sure that is intentional.

@Muennighoff I have added the bare minimum here for running models, we also need to add a point for coordination. I imagine there might also have been other contributors (Sara Hooker) who have spent time on the paper, which we might want to add in as well.

### CODE REVIEW

**Comment by isaac-chung** [comment]
Yep that's intentional. Thanks for checking in.

**Comment by KennethEnevoldsen** [comment]
Good to know. I will also check with @awinml, @Ruqyai, @achibb, @guangyusong, @wissam-sib, @GabrielSequeira, and @Sakshamrzt

Let me know if any of you would like to update your affiliation or simply leave it blank. It blank is fine feel free to just respond with a thumbs up

**Comment by Muennighoff** [comment]
Looks great! Yes, could we add some points for the below. You probably know best how much, I think just guestimating should be fine where it is difficult to pin down.
- @sarahooker for paper editing (can probably check the Overleaf history to get a sense of how much)
- @swj0419 & @xiamengzhou for this PR https://github.com/embeddings-benchmark/mteb/pull/971 (if we treat each as a separate task like in https://github.com/embeddings-benchmark/mteb/pull/972/files#diff-dd2649fdf798ea23a8ad7d3b8aaaa8c77ae78868f3293f06dae5b5e97e4a323c, it'd be 12*2 but maybe it's done differently; again you probably know best)
- As you said, maybe points for coordination...your own count would probably be double or triple of what it is 😁
- Maybe other things missing 🤔

**Comment by wissam-sib** [comment]
@KennethEnevoldsen thanks for checking. I'm fine leaving my affiliation blank. Just noticed my email has a typo (should be wissam.siblini92@gmail.com). And my open review is '~Wissam_Siblini1'. Would you like me to update these?

**Comment by guangyusong** [comment]
> Good to know. I will also check with @awinml, @achibb, @guangyusong, @wissam-sib, @GabrielSequeira, and @Sakshamrzt
> 
> Let me know if any of you would like to update your affiliation or simply leave it blank. It blank is fine feel free to just respond with a thumbs up

Could you please update it to `Tano Labs`. Thank you!

**Comment by gentaiscool** [comment]
Could you change my email address to "gentaindrawinata@gmail.com" instead? thanks @KennethEnevoldsen

**Comment by KennethEnevoldsen** [comment]
- @wissam-sib it would be great if you 

> @sarahooker for paper editing (can probably check the Overleaf history to get a sense of how much)

I found the edit by @sarahooker very helpful (I have added 10 points for those). @sarahooker if you have the time I would love a second look at the paper once we have added the last details.

@gentaiscool, @guangyusong , @wissam-sib I have updated the tables 

> As you said, maybe points for coordination...your own count would probably be double or triple of what it is 😁

Will probably do points for coordination in a separate PR to allow people some time to discuss this.

**Review by imenelydiaker — APPROVED** [review]
Great thanks @KennethEnevoldsen!

**Pull request merged**
