### PR TITLE
Added new dataset: TenKGnadClassification

### PR DESCRIPTION
**Pull request by malteos**
10k German News Articles Dataset (10kGNAD) contains news articles from the online Austrian newspaper website DER Standard with their topic classification (9 classes).

## Checklist for adding MMTEB dataset

Reason for dataset addition: Classification task for the 10kGnad dataset

- [x] I have tested that the dataset runs with the `mteb` package.
- [x] I have run the following models on the task (adding the results to the pr). These can be run using the `mteb run -m {model_name} -t {task_name}` command.
  - [x] `sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2`
  - [x] `intfloat/multilingual-e5-small`
- [x] I have checked that the performance is neither trivial (both models gain close to perfect scores) nor random (both models gain close to random scores).
- [x] If the dataset is too big (e.g. >2048 examples), considering using `self.stratified_subsampling() under dataset_transform()`
- [x] I have filled out the metadata object in the dataset file (find documentation on it [here](https://github.com/embeddings-benchmark/mteb/blob/main/docs/adding_a_dataset.md#2-creating-the-metadata-object)).
- [x] Run tests locally to make sure nothing is broken using `make test`. 
- [x] Run the formatter to format the code using `make lint`. 
- [ ] I have added points for my submission to the [points folder](https://github.com/embeddings-benchmark/mteb/blob/main/docs/mmteb/points.md) using the PR number as the filename (e.g. `438.jsonl`).

Since there is already clustering task for this dataset, how many points does this submission get?

### CODE REVIEW

**Review by KranthiGV — APPROVED** [review]
LGTM

**Review by isaac-chung — APPROVED** [review]
Thanks for adding this! Feel free to add the points (2 for the dataset, and 2 for each reviewer). 

We hope to expand other tasks (e.g. multilabel classification / Reranking etc). Would be great to see you contribute to those as well :)

**Review by Ruqyai — APPROVED** [review]

**Comment by Ruqyai** [comment]
LGTM

**Comment by KennethEnevoldsen** [comment]
I will merge this for now. @isaac-chung or @malteos feel free to create a PR for the points

**Pull request merged**
