### PR TITLE
fix: Update COIR datasets 

### PR DESCRIPTION
**Pull request by monikernemo**
1. Changed source hf repo from mteb to coir for easier future maintenance and bug fix (primarily, removal of title in CodeSearchNet-CCR Ruby) 
2. Included CodeSearchNet dataset as part of COIR (COIR uses CodeSearchNet to retrieve code summary given a code snippet) 

## Checklist

- [x] Run tests locally to make sure nothing is broken using `make test`. 
- [x] Run the formatter to format the code using `make lint`. 

### Adding datasets checklist

**Reason for dataset addition**: Added **COIRCodeSearchNet**; COIR intended to use code snippets in CodeSearchNet to retrieve relevant code docstrings / code summary. 

- [x] I have run the following models on the task (adding the results to the pr). These can be run using the `mteb -m {model_name} -t {task_name}` command.
  - [x] `intfloat/e5-base-v2`
- [x] I have checked that the performance is neither trivial (both models gain close to perfect scores) nor random (both models gain close to random scores).
- [x] If the dataset is too big (e.g. >2048 examples), considering using `self.stratified_subsampling() under dataset_transform()`
- [x] I have filled out the metadata object in the dataset file (find documentation on it [here](https://github.com/embeddings-benchmark/mteb/blob/main/docs/adding_a_dataset.md#2-creating-the-metadata-object)).
- [x] Run tests locally to make sure nothing is broken using `make test`. 
- [x] Run the formatter to format the code using `make lint`.

### CODE REVIEW

**Review by Samoed — APPROVED** [review]
Are there any differences between your code-search-net and the original? Also, why don't you include the title in your models, especially since mteb passes the title as part of the text to the models? https://github.com/embeddings-benchmark/mteb/blob/fae93048a39c52d489ce38b66720f4a994f525ab/mteb/evaluation/evaluators/RetrievalEvaluator.py#L380-L393

**Comment by monikernemo** [comment]
> Are there any differences between your code-search-net and the original? 
As mentioned, the original code-search-net task retrieves relevant code snippets from a given docstring; here we use the code snippets to retrieve relevant code description / summary in text. 

> Also, why don't you include the title in your models, especially since mteb passes the title as part of the text to the models?
We were focused on textual information as such we did not consider any meta-information to be used for retrieval.

**Comment by KennethEnevoldsen** [comment]
@monikernemo seems like we need to update benchmark.py (already added in https://github.com/embeddings-benchmark/mteb/pull/1142)

**Comment by monikernemo** [comment]
> @monikernemo seems like we need to update benchmark.py (already added in #1142)

Done.

**Comment by monikernemo** [comment]
> @monikernemo seems like we need to update benchmark.py (already added in #1142)

done!

**Review by KennethEnevoldsen — APPROVED** [review]
lgtm

**Pull request merged**
