### PR TITLE
[MIEB] Add image clustering

### PR DESCRIPTION
**Pull request by isaac-chung**
## Checklist

- [x] Run tests locally to make sure nothing is broken using `make test`. 
- [x] Run the formatter to format the code using `make lint`. 

### Adding datasets checklist

**Reason for dataset addition**: ... 

- [x] I have run the following models on the task (adding the results to the pr). These can be run using the `mteb -m {model_name} -t {task_name}` command.
  - [ ] `sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2`
  - [ ] `intfloat/multilingual-e5-small`
- [x] I have checked that the performance is neither trivial (both models gain close to perfect scores) nor random (both models gain close to random scores).
- [x] If the dataset is too big (e.g. >2048 examples), considering using `self.stratified_subsampling() under dataset_transform()`
- [x] I have filled out the metadata object in the dataset file (find documentation on it [here](https://github.com/embeddings-benchmark/mteb/blob/main/docs/adding_a_dataset.md#2-creating-the-metadata-object)).
- [x] Run tests locally to make sure nothing is broken using `make test`. 
- [x] Run the formatter to format the code using `make lint`.

### CODE REVIEW

**Comment by gowitheflow-1998** [comment]
looks amazing! Thanks for adding these. It seems like image clustering typically uses NMI, ARI and accuracy as metrics such as [benchmark](https://paperswithcode.com/sota/image-clustering-on-imagenet) [benchmark](https://paperswithcode.com/sota/image-clustering-on-tiny-imagenet) [paper](https://openaccess.thecvf.com/content_ICCV_2017/papers/Chang_Deep_Adaptive_Image_ICCV_2017_paper.pdf) [paper](https://arxiv.org/pdf/2402.10093v2) [paper](https://arxiv.org/pdf/2303.17896v2). Will be good to add support for these. Otherwise all good!

**Review by gowitheflow-1998 — APPROVED** [review]

**Comment by isaac-chung** [comment]
@gowitheflow-1998 I think there's an error when we run `make test` from `tests/test_all_abstasks.py::test_load_data` on the `MSCOCOI2TRetrieval` task. Could you please take a look when you have a chance?

**Comment by gowitheflow-1998** [comment]
> @gowitheflow-1998 I think there's an error when we run `make test` from `tests/test_all_abstasks.py::test_load_data` on the `MSCOCOI2TRetrieval` task. Could you please take a look when you have a chance?

@isaac-chung The problem was `load_dataset` detected not called by AbsTaskI2TRetrieval, which should also be ignored following previous tests in main. I'll add `or isinstance(task, AbsTaskI2TRetrieval)` in `test_all_abstasks.py` if you could pull and push again after adding metrics?

```python
def test_load_data(
    mock_concatenate_datasets: Mock, mock_load_dataset: Mock, task: AbsTask
):
    # TODO: We skip because this load_data is completely different.
    if (
        isinstance(task, AbsTaskRetrieval)
        or isinstance(task, AbsTaskI2TRetrieval)
        or isinstance(task, AbsTaskInstructionRetrieval)
        or isinstance(task, MultiSubsetLoader)
        or isinstance(task, AbsTaskSpeedTask)
    ):
        pytest.skip()
```

**Comment by isaac-chung** [comment]
@gowitheflow-1998 thanks! Tests are passing now.

I've added accuracy for Tiny ImageNet. I think any additional metrics can be added along with the datasets that use them? I feel that this can be merged now and we can iterate.

**Pull request merged**
