### PR TITLE
add SFR embed model

### PR DESCRIPTION
**Pull request by isaac-chung**
Addresses part of https://github.com/embeddings-benchmark/arena/issues/6

## Checklist

- [x] Run tests locally to make sure nothing is broken using `make test`. 
- [x] Run the formatter to format the code using `make lint`. 

### Adding a model checklist

 - [x] I have filled out the ModelMeta object to the extent possible
 - [x] I have ensured that my model can be loaded using
   - [x] `mteb.get_model(model_name, revision_id)` and
   - [x] `mteb.get_model_meta(model_name, revision_id)`
 - [x] I have tested the implementation works on a representative set of tasks.

### CODE REVIEW

**Review by Muennighoff — COMMENTED** [review]
Nice! I think it is missing last token pooling, no?

**Comment by isaac-chung** [comment]
It seems like [Tom's PR](https://huggingface.co/Salesforce/SFR-Embedding-2_R/discussions/1) added it to the model. To confirm, printing the model shows:
```
MODEL: 
 SentenceTransformer(
  (0): Transformer({'max_seq_length': 4096, 'do_lower_case': False}) with Transformer model: MistralModel 
  (1): Pooling({'word_embedding_dimension': 4096, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': False, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': True, 'include_prompt': True})
)
```

However, I wasn't able to reproduce any numbers from the example script nor from the reported evaluations. e.g. for the example script:
```python
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("Salesforce/SFR-Embedding-2_R")

def get_detailed_instruct(task_description: str, query: str) -> str:
    return f'Instruct: {task_description}\nQuery: {query}'

# Each query must come with a one-sentence instruction that describes the task
task = 'Given a web search query, retrieve relevant passages that answer the query'
queries = [
    get_detailed_instruct(task, 'How to bake a chocolate cake'),
    get_detailed_instruct(task, 'Symptoms of the flu')
]
# No need to add instruction for retrieval documents
passages = [
    "To bake a delicious chocolate cake, you'll need the following ingredients: all-purpose flour, sugar, cocoa powder, baking powder, baking soda, salt, eggs, milk, vegetable oil, and vanilla extract. Start by preheating your oven to 350°F (175°C). In a mixing bowl, combine the dry ingredients (flour, sugar, cocoa powder, baking powder, baking soda, and salt). In a separate bowl, whisk together the wet ingredients (eggs, milk, vegetable oil, and vanilla extract). Gradually add the wet mixture to the dry ingredients, stirring until well combined. Pour the batter into a greased cake pan and bake for 30-35 minutes. Let it cool before frosting with your favorite chocolate frosting. Enjoy your homemade chocolate cake!",
    "The flu, or influenza, is an illness caused by influenza viruses. Common symptoms of the flu include a high fever, chills, cough, sore throat, runny or stuffy nose, body aches, headache, fatigue, and sometimes nausea and vomiting. These symptoms can come on suddenly and are usually more severe than the common cold. It's important to get plenty of rest, stay hydrated, and consult a healthcare professional if you suspect you have the flu. In some cases, antiviral medications can help alleviate symptoms and reduce the duration of the illness."
]

embeddings = model.encode(queries + passages)
scores = model.similarity(embeddings[:2], embeddings[2:]) * 100
print(scores.tolist())
# [[40.13203811645508, 25.032546997070312], [15.00684642791748, 39.937339782714844]]
```

I got instead:
```python
# [[79.51383972167969, 32.043087005615234], [30.606239318847656, 74.47332000732422]]
```

using these versions on linux:
```
pip freeze | grep transformers
sentence-transformers==3.0.1
transformers==4.41.2
```

**Comment by Muennighoff** [comment]
Oh nice!

Hmm we should be able to reproduce the example script at least - if you run the [example script](https://huggingface.co/Salesforce/SFR-Embedding-2_R#transformers) with the same env you use for running it in MTEB do you get the same result? Maybe printing out exactly what goes into the model in mteb could help.

**Comment by isaac-chung** [comment]
Running the example transformers script, ST script, and running it in MTEB obtain the same results:
```
# [[79.51383972167969, 32.043087005615234], [30.606239318847656, 74.47332000732422]]
```

So at least the implementations agree 😄

**Review by Muennighoff — APPROVED** [review]
Seems good then, let's merge?

**Pull request merged**
