### PR TITLE
Fix identical query-corpus ids in retrieval tasks

### PR DESCRIPTION
**Pull request by akshita-sukhlecha**
## Checklist

- [x] Run tests locally to make sure nothing is broken using `make test`. 
- [x] Run the formatter to format the code using `make lint`. 
- [x] Validated : new results are very much similar to old results.

### CODE REVIEW

**Comment by KennethEnevoldsen** [comment]
@akshita-sukhlecha this might relate to #833 (@imenelydiaker adding you here as well)

**Review by imenelydiaker — COMMENTED** [review]
LGTM! Soms ids weren't built correctly. 

Just to make sure, no language scpecific benchmark uses these two datasets? Else, we'll have to run all evals again :/

**Comment by KennethEnevoldsen** [comment]
@akshita-sukhlecha will you pull from main to see if all tests pass?

**Comment by akshita-sukhlecha** [comment]
I pulled the changes from main and ran the tests. 

`[test_mteb_with_instructions` test cases](https://github.com/embeddings-benchmark/mteb/blob/main/tests/test_mteb.py#L92) were failing ... because Encoder now requires the **device** param in constructor. 
I pushed another commit to make this param optional.

**Pull request merged**
