### PR TITLE
reuse corpus utils for LLM2Vec

### PR DESCRIPTION
**Pull request by bzantium**
resolved: #1039

## Checklist

- [x] Run tests locally to make sure nothing is broken using `make test`. 
- [x] Run the formatter to format the code using `make lint`.

### CODE REVIEW

**Review by dokato — CHANGES_REQUESTED** [review]
Lint needs fixing, otherwise LGTM.

**Comment by bzantium** [comment]
I just pushed lint commit! thanks for the comment :)

**Comment by KennethEnevoldsen** [comment]
@vaibhavad it is probably best that you review. Everything looks alright. One thing is that it ties model implementations together and I would probably argue that we want to make sure we can edit in LLM2Vec without considering other models, so there is def. no need to utilize the utils.

**Comment by vaibhavad** [comment]
LGTM. @KennethEnevoldsen I think as long as functions are being used from utils, it is fine. Document processing is very similar across models.

**Review by vaibhavad — APPROVED** [review]

**Comment by KennethEnevoldsen** [comment]
wanted to merge this PR but seems like I can't - @vaibhavad feel free to merge it is you can

**Comment by bzantium** [comment]
@vaibhavad please merge if you are okay :)

**Pull request merged**
