### PR TITLE
WIP: Leaderboard UI improvements

### PR DESCRIPTION
**Pull request by x-tabdeveloping**
I'm opening this PR so that you can track my progress in ironing out some of the UI problems in the Leaderboard.

### CODE REVIEW

**Comment by x-tabdeveloping** [comment]
I'm cookin' this is how it lookin'
image

**Comment by x-tabdeveloping** [comment]
I could finally add a scrollbar. It is completely beyond me which Gradio elements are okay with scrolling and why, but `gr.Row()` works for some reason. (`CheckBox`, `Group` and `Column` don't)

**Comment by KennethEnevoldsen** [comment]
A couple of comments for readability:

- remove org from model name (and add reference link #1316)
- multiply scores by 100 and keep one decimal, e.g. 78.1 (@orionw not sure if this also works for followIR?). I believe anything more precise does not translate to a meaningful performance difference
- It might be ideal to move the "performance pr. task" to a separate table in a fold-down menu.

Let me know if you want this to be an issue

**Comment by x-tabdeveloping** [comment]
@KennethEnevoldsen can we make it an issue?
Thanks for the comments btw

**Comment by KennethEnevoldsen** [comment]
done!

**Pull request merged**
