### PR TITLE
Removing OpusParcus task for PairClassification

### PR DESCRIPTION
**Pull request by imenelydiaker**
Related to this issue #334 

Removing OpusParcus because it is too trivial (at least it is for French). I assume it is the same for other languages. 

The dataset consists of paraphrases of movies subtitles, it originally contains scores from 1 to 4 to rate the quality of the praphrase (paraphrases with scores 3 and 4 are considered good paraphrases, others not).

Sentences are short and maybe with the pair classification task setup (saying whether a sentence is a paraphrase or not), it becomes easy.

### CODE REVIEW

**Comment by KennethEnevoldsen** [comment]
I believe you are right as a pair classification task it seems way too easy.

**Review by KennethEnevoldsen — APPROVED** [review]
-

**Comment by imenelydiaker** [comment]
Results for English (`sentence-bert-base`):
```
{
  "dataset_revision": "9e9b1f8ef51616073f47f306f7f47dd91663f86a",
  "mteb_dataset_name": "OpusparcusPC",
  "mteb_version": "1.6.1",
  "test.full": {
    "en": {
      "cos_sim": {
        "accuracy": 0.9310089020771514,
        "accuracy_threshold": 0.8042856454849243,
        "ap": 0.9886188196706145,
        "f1": 0.9532898041185335,
        "f1_threshold": 0.8034826517105103,
        "precision": 0.9405351833498513,
        "recall": 0.9663951120162932
      },
      "dot": {
        "accuracy": 0.9310089020771514,
        "accuracy_threshold": 0.8042857050895691,
        "ap": 0.9886188196706145,
        "f1": 0.9532898041185335,
        "f1_threshold": 0.8034826517105103,
        "precision": 0.9405351833498513,
        "recall": 0.9663951120162932
      },
      "euclidean": {
        "accuracy": 0.9310089020771514,
        "accuracy_threshold": 0.6256418824195862,
        "ap": 0.9886188196706145,
        "f1": 0.9532898041185335,
        "f1_threshold": 0.6269248127937317,
        "precision": 0.9405351833498513,
        "recall": 0.9663951120162932
      },
      "manhattan": {
        "accuracy": 0.9295252225519288,
        "accuracy_threshold": 13.334480285644531,
        "ap": 0.988748298616027,
        "f1": 0.9526184538653365,
        "f1_threshold": 14.069385528564453,
        "precision": 0.9335288367546432,
        "recall": 0.9725050916496945
      },
      "max": {
        "accuracy": 0.9310089020771514,
        "ap": 0.988748298616027,
        "f1": 0.9532898041185335
      }
    },
    "evaluation_time": 111.21
  },
  "validation.full": {
    "en": {
      "cos_sim": {
        "accuracy": 0.9237037037037037,
        "accuracy_threshold": 0.7976409196853638,
        "ap": 0.9876739198507991,
        "f1": 0.9505520883341335,
        "f1_threshold": 0.7976409196853638,
        "precision": 0.9269662921348315,
        "recall": 0.9753694581280788
      },
      "dot": {
        "accuracy": 0.9237037037037037,
        "accuracy_threshold": 0.7976409792900085,
        "ap": 0.9876739198507991,
        "f1": 0.9505520883341335,
        "f1_threshold": 0.7976409792900085,
        "precision": 0.9269662921348315,
        "recall": 0.9753694581280788
      },
      "euclidean": {
        "accuracy": 0.9237037037037037,
        "accuracy_threshold": 0.6361744999885559,
        "ap": 0.9876739198507991,
        "f1": 0.9505520883341335,
        "f1_threshold": 0.6361744999885559,
        "precision": 0.9269662921348315,
        "recall": 0.9753694581280788
      },
      "manhattan": {
        "accuracy": 0.9237037037037037,
        "accuracy_threshold": 13.779753684997559,
        "ap": 0.9875569838446521,
        "f1": 0.9500727096461464,
        "f1_threshold": 13.779753684997559,
        "precision": 0.9351145038167938,
        "recall": 0.9655172413793104
      },
      "max": {
        "accuracy": 0.9237037037037037,
        "ap": 0.9876739198507991,
        "f1": 0.9505520883341335
      }
    },
    "evaluation_time": 114.38
  }
}
```

@KennethEnevoldsen can you confirm it is not trivial?

**Comment by imenelydiaker** [comment]
Results for English (`average_word_embeddings_komninos`):
```
{
  "dataset_revision": "9e9b1f8ef51616073f47f306f7f47dd91663f86a",
  "mteb_dataset_name": "OpusparcusPC",
  "mteb_version": "1.6.1",
  "test.full": {
    "en": {
      "cos_sim": {
        "accuracy": 0.755192878338279,
        "accuracy_threshold": 0.3628547489643097,
        "ap": 0.9050660115769191,
        "f1": 0.8451557093425606,
        "f1_threshold": 0.13603007793426514,
        "precision": 0.7345864661654136,
        "recall": 0.994908350305499
      },
      "dot": {
        "accuracy": 0.7433234421364985,
        "accuracy_threshold": 4.781040191650391,
        "ap": 0.9049616655895583,
        "f1": 0.8432803778445684,
        "f1_threshold": 0.0,
        "precision": 0.7290274684484038,
        "recall": 1.0
      },
      "euclidean": {
        "accuracy": 0.7329376854599406,
        "accuracy_threshold": 5.505668640136719,
        "ap": 0.874629513716229,
        "f1": 0.8434670116429496,
        "f1_threshold": 6.43278694152832,
        "precision": 0.7314884068810771,
        "recall": 0.9959266802443992
      },
      "manhattan": {
        "accuracy": 0.733679525222552,
        "accuracy_threshold": 74.48164367675781,
        "ap": 0.8738617737898778,
        "f1": 0.8434670116429496,
        "f1_threshold": 89.55355834960938,
        "precision": 0.7314884068810771,
        "recall": 0.9959266802443992
      },
      "max": {
        "accuracy": 0.755192878338279,
        "ap": 0.9050660115769191,
        "f1": 0.8451557093425606
      }
    },
    "evaluation_time": 0.25
  },
  "validation.full": {
    "en": {
      "cos_sim": {
        "accuracy": 0.7681481481481481,
        "accuracy_threshold": 0.3081892132759094,
        "ap": 0.8960087702301884,
        "f1": 0.8617886178861789,
        "f1_threshold": 0.1646978259086609,
        "precision": 0.7617246596066566,
        "recall": 0.9921182266009853
      },
      "dot": {
        "accuracy": 0.7511111111111111,
        "accuracy_threshold": 0.0,
        "ap": 0.9002447960066425,
        "f1": 0.8578680203045684,
        "f1_threshold": 0.0,
        "precision": 0.7516679021497406,
        "recall": 0.9990147783251232
      },
      "euclidean": {
        "accuracy": 0.7548148148148148,
        "accuracy_threshold": 5.545105457305908,
        "ap": 0.8714340293922218,
        "f1": 0.8588435374149659,
        "f1_threshold": 6.1913933753967285,
        "precision": 0.7554225878833208,
        "recall": 0.9950738916256158
      },
      "manhattan": {
        "accuracy": 0.7548148148148148,
        "accuracy_threshold": 78.53974151611328,
        "ap": 0.8708158494720002,
        "f1": 0.8588384908859688,
        "f1_threshold": 87.33755493164062,
        "precision": 0.7537202380952381,
        "recall": 0.9980295566502463
      },
      "max": {
        "accuracy": 0.7681481481481481,
        "ap": 0.9002447960066425,
        "f1": 0.8617886178861789
      }
    },
    "evaluation_time": 0.15
  }
}
```

**Comment by KennethEnevoldsen** [comment]
Hmm maybe rather I would rather run it with the two models recommended for new dataset (they are both competent multilingual models, which are not perfect). If any of them gain close to perfect performance I believe the dataset has a cealing effect.

**Comment by MartinBernstorff** [comment]
@KennethEnevoldsen Completely agree here.

On reflection, do we want to exclude any dataset with ceiling effects for `e5-small`? On the surface it seems very reasonable, since we expect models to get better over time. But I wouldn't want to exclude the only task for a given language because it is too easy.

We can probably do it on a case-by-case basis.

**Comment by KennethEnevoldsen** [comment]
I am not proposing a general rule. In this case, I would remove it if e5-small gains close to perfect performance as we have other tasks both on the same data and for the language.

**Comment by ManuelFay** [comment]
For french with the multilingual-e5-small, I got:
```bash
INFO:mteb.evaluation.MTEB:Evaluation for OpusparcusPC on test.full took 2.92 seconds
INFO:mteb.evaluation.MTEB:Scores: {'fr': {'cos_sim': {'accuracy': 0.8113079019073569, 'accuracy_threshold': 0.8920607566833496, 'f1': 0.8679585398828302, 'f1_threshold': 0.872085452079773, 'precision': 0.7945544554455446, 'recall': 0.9563058589870904, 'ap': 0.9251631850374396}, 'manhattan': {'accuracy': 0.80858310626703, 'accuracy_threshold': 7.636565208435059, 'f1': 0.8700878409616273, 'f1_threshold': 7.636565208435059, 'precision': 0.8140138408304498, 'recall': 0.9344587884806356, 'ap': 0.9238098841988499}, 'euclidean': {'accuracy': 0.8113079019073569, 'accuracy_threshold': 0.464627206325531, 'f1': 0.8679585398828302, 'f1_threshold': 0.5057953596115112, 'precision': 0.7945544554455446, 'recall': 0.9563058589870904, 'ap': 0.9251631850374396}, 'dot': {'accuracy': 0.8113079019073569, 'accuracy_threshold': 0.8920607566833496, 'f1': 0.8679585398828302, 'f1_threshold': 0.872085452079773, 'precision': 0.7945544554455446, 'recall': 0.9563058589870904, 'ap': 0.9251631850374396}, 'max': {'accuracy': 0.8113079019073569, 'f1': 0.8700878409616273, 'ap': 0.9251631850374396}}, 'evaluation_time': 2.92}
```

So non-trivial I would say !

**Comment by imenelydiaker** [comment]
I'm closing this PR if everyone agrees, and I'll open a new one to update results of all models on this task.

**Comment by imenelydiaker** [comment]
I know what happened here, during the experiments we loaded the `test` split instead of the `test.full` split (due to an automation to run the whole benchmark). The `test` split exists so there wasn't any error, it contains only positive pairs, and appearently all models were good on finding them. They seem to struggle more with negative pairs (these are included in the `test.full` split).

**Pull request closed without merging**
