### PR TITLE
Fix : Error [test_all_metadata_is_filled ]

### PR DESCRIPTION
**Pull request by Ruqyai**
Screenshot 2024-05-18 at 7 33 30 AM
#762 

https://github.com/embeddings-benchmark/mteb/pull/669#issuecomment-2117932543

### CODE REVIEW

**Comment by KennethEnevoldsen** [comment]
@Ruqyai seems like you are submitting more than just a fix in this PR (it includes a dataset as well)

**Comment by Ruqyai** [comment]
> @Ruqyai seems like you are submitting more than just a fix in this PR (it includes a dataset as well)

After I opened the PR I noticed that :') as well

**Comment by KennethEnevoldsen** [comment]
@Ruqyai will close this PR as I am not sure what it adds. Please make another PR where you explain what is being added and why.

**Comment by Ruqyai** [comment]
Thank you @KennethEnevoldsen . I will do

**Pull request closed without merging**
