### PR TITLE
Fixes MultilabelClassification eval_split

### PR DESCRIPTION
**Pull request by dokato**
This fixes bug reported in https://github.com/embeddings-benchmark/mteb/issues/810 and caused by https://github.com/embeddings-benchmark/mteb/pull/759 .

Not sure if this is the best approach but since old eval_split was working I just copied it from classification abstask.

### CODE REVIEW

**Comment by isaac-chung** [comment]
This is ok for the short term. 
To confirm that it actually works, could you please add `MalteseNewsClassification` in `tests/test_mteb.py` as one of the test tasks? (the list starts on line 30)

**Review by isaac-chung — COMMENTED** [review]
This is ok for the short term. 
To confirm that it actually works, could you please add `MalteseNewsClassification` in `tests/test_mteb.py` as one of the test tasks? (the list starts on line 30)

**Comment by dokato** [comment]
Done ✅

**Comment by imenelydiaker** [comment]
> This is ok for the short term. To confirm that it actually works, could you please add `MalteseNewsClassification` in `tests/test_mteb.py` as one of the test tasks? (the list starts on line 30)


Actually the `evaluate` method was removed by mistake in #759, I think @dokato just put it back so it should be good

**Review by isaac-chung — APPROVED** [review]
Thanks!

**Pull request merged**
