### PR TITLE
Feature/custombeirmodel

### PR DESCRIPTION
**Pull request by Muennighoff**
Some models like OpenAI's API endpoint or SGPT use separate encoding functions for Query & Corpus, so this is useful imo.

A notebook example:

```python
!pip install -q git+https://github.com/muennighoff/mteb.git@feature/custombeirmodel
!pip install -q git+https://github.com/beir-cellar/beir.git
!pip install -q evaluate
!pip install --upgrade git+https://github.com/Muennighoff/sentence-transformers.git@sgpt_poolings_specb
```
```python
%%writefile xxx.py

from mteb import BeIRModel
from typing import Dict, List, Union, Tuple

import numpy as np
from sentence_transformers import SentenceTransformer, models
from torch import Tensor


class SentenceBERTBOSEOS(BeIRModel):
    def __init__(self, model_path: Union[str, Tuple] = None, sep: str = " ", **kwargs):
        self.sep = sep
        self.model = SentenceTransformer(model_path, **kwargs)

        word_embedding_model = self.model._first_module()
        assert isinstance(word_embedding_model, models.Transformer)

        tokens = ["[SOS]", "{SOS}"]
        word_embedding_model.tokenizer.add_tokens(tokens, special_tokens=True)
        word_embedding_model.auto_model.resize_token_embeddings(len(word_embedding_model.tokenizer))

        # Will be replaced with the rep ones
        word_embedding_model.bos_spec_token_q = word_embedding_model.tokenizer.encode("[SOS]", add_special_tokens=False)[0]
        word_embedding_model.bos_spec_token_d = word_embedding_model.tokenizer.encode("{SOS}", add_special_tokens=False)[0]

        word_embedding_model.bos_spec_token_q_rep = word_embedding_model.tokenizer.encode("[", add_special_tokens=False)[0]
        word_embedding_model.eos_spec_token_q = word_embedding_model.tokenizer.encode("]", add_special_tokens=False)[0]
        
        word_embedding_model.bos_spec_token_d_rep = word_embedding_model.tokenizer.encode("{", add_special_tokens=False)[0]
        word_embedding_model.eos_spec_token_d = word_embedding_model.tokenizer.encode("}", add_special_tokens=False)[0]

        word_embedding_model.replace_bos = True

    def encode_queries(self, queries: List[str], batch_size: int = 16, **kwargs) -> Union[List[Tensor], np.ndarray, Tensor]:
        # Will be replaced with [ in the models tokenization
        # If we would put [ here, there is a risk of it getting chained with a different token when encoding
        queries = ["[SOS]" + q for q in queries]
        return self.model.encode(queries, batch_size=batch_size, **kwargs)
    
    def encode_corpus(self, corpus: List[Dict[str, str]], batch_size: int = 8, **kwargs) -> Union[List[Tensor], np.ndarray, Tensor]:
        # Will be replaced with { in the models tokenization
        # If we would put { here, there is a risk of it getting chained with a different token when encoding
        sentences = [("{SOS}" + doc["title"] + self.sep + doc["text"]).strip() if "title" in doc else "{SOS}" + doc["text"].strip() for doc in corpus]
        return self.model.encode(sentences, batch_size=batch_size, **kwargs)

    def encode_corpus_parallel(
        self, corpus: List[Dict[str, str]], pool: Dict[str, object], batch_size: int, chunk_id: int, **kwargs
    ):
        if type(corpus) is dict:
            sentences = [
                ("{SOS}" + corpus["title"][i] + self.sep + corpus["text"][i]).strip()
                if "title" in corpus
                else "{SOS}" + corpus["text"][i].strip()
                for i in range(len(corpus["text"]))
            ]
        else:
            sentences = [
                ("{SOS}" + doc["title"] + self.sep + doc["text"]).strip() if "title" in doc else "{SOS}" + doc["text"].strip()
                for doc in corpus
            ]

        if chunk_id is not None and chunk_id >= len(pool["processes"]):
            output_queue = pool["output"]
            output_queue.get()

        input_queue = pool["input"]
        input_queue.put([chunk_id, batch_size, sentences])


from mteb.abstasks import AbsTaskRetrieval

assert AbsTaskRetrieval.is_beir_compatible(SentenceBERTBOSEOS, is_parallel=True)


from mteb import MTEB

model_name = "Muennighoff/SGPT-125M-weightedmean-msmarco-specb-bitfit"
model = SentenceBERTBOSEOS(model_name)
evaluation = MTEB(tasks=["SciFact"])
results = evaluation.run(model, output_folder=f"results/{model_name}")
```
```
!python xxx.py
```

### CODE REVIEW

**Review by NouamaneTazi — CHANGES_REQUESTED** [review]
The methods you check in `BEIR_METHODS` and `BEIR_METHODS_PARALLEL` are actually required for `DRPES` or `DRES` to run and not all BEIR models. We should probably consider renaming BEIR models to DRES models at some point. Wdyt?

**Comment by Muennighoff** [comment]
> The methods you check in `BEIR_METHODS` and `BEIR_METHODS_PARALLEL` are actually required for `DRPES` or `DRES` to run and not all BEIR models. We should probably consider renaming BEIR models to DRES models at some point. Wdyt?

Good point - Did I address it like you meant?

**Comment by Muennighoff** [comment]
I will merge this - ok?

**Comment by NouamaneTazi** [comment]
Yes please go ahead!

**Review by NouamaneTazi — APPROVED** [review]

**Pull request merged**
