### PR TITLE
fix: ensure that results from parallel datasets are formatted correctly

### LINKED ISSUE #969: KeyError: 'default'
Got the below error when running https://github.com/embeddings-benchmark/mteb/blob/main/scripts/mmteb/running_model/create_slurm_jobs.py
```bash
INFO:mteb.cli:Running with parameters: Namespace(model='sentence-transformers/all-MiniLM-L6-v2', task_types=None, categories=None, tasks=['FloresBitextMining'], languages=None, device=None, output_folder='/data/niklas/mteb/results', verbosity=2, co2_tracker=True, eval_splits=None, model_revision=None, func=<function run at 0x7f75f4d4f400>)
/env/lib/conda/gritkto/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
INFO:mteb.evaluation.MTEB:

## Evaluating 1 tasks:
─────────────────────────────── Selected tasks  ────────────────────────────────
BitextMining
    - FloresBitextMining, s2s, multilingual 41412 / 41412 langs


INFO:mteb.evaluation.MTEB:

********************** Evaluating FloresBitextMining **********************

.....shortened.....


ERROR:mteb.evaluation.MTEB:Error while evaluating FloresBitextMining: 'default'
Traceback (most recent call last):
  File "/env/lib/conda/gritkto/bin/mteb", line 8, in <module>
    sys.exit(main())
  File "/data/niklas/mteb/mteb/cli.py", line 362, in main
    args.func(args)
  File "/data/niklas/mteb/mteb/cli.py", line 118, in run
    eval.run(
  File "/data/niklas/mteb/mteb/evaluation/MTEB.py", line 388, in run
    raise e
  File "/data/niklas/mteb/mteb/evaluation/MTEB.py", line 367, in run
    mteb_task_result = MTEBResults.from_task_results(
  File "/data/niklas/mteb/mteb/MTEBResults.py", line 89, in from_task_results
    eval_langs = subset2langscripts[hf_subset]
KeyError: 'default'

```

### PR DESCRIPTION
**Pull request by KennethEnevoldsen**
Additionally updated a few print statements to make them more clear (or correct).

fixes #969

@Muennighoff note that this also fix issue from other parallel bitext tasks (which will fail when they try to write their results). A solution in the future would def. be to iteratively write results instead of writing all the results at once.

## Checklist

- [x] Run tests locally to make sure nothing is broken using `make test`. 
- [x] Run the formatter to format the code using `make lint`.

### CODE REVIEW

**Review by Muennighoff — COMMENTED** [review]
Great! It's weird that tests were passing previously despite this issue? Do we need to adjust something in the tests to catch this in the future? 🤔

The result files are pretty huge, maybe we should remove them if we [don't keep them in this repo](https://github.com/embeddings-benchmark/mteb/pull/953)? 😁

**Review by isaac-chung — APPROVED** [review]
Great! We might not have covered the `parallel_subsets` part of AbsTaskBitextMining in the test cases. We could potentially look at test coverage to address what's missing?

**Comment by isaac-chung** [comment]
e.g. running `pytest --cov-report term --cov=mteb/abstasks tests/`, we get
```
---------- coverage: platform linux, python 3.11.4-final-0 -----------
Name                                               Stmts   Miss  Cover
----------------------------------------------------------------------
mteb/abstasks/AbsTask.py                             111     26    77%
mteb/abstasks/AbsTaskBitextMining.py                  35      5    86%
mteb/abstasks/AbsTaskClassification.py                69      5    93%
mteb/abstasks/AbsTaskClustering.py                    26      0   100%
mteb/abstasks/AbsTaskClusteringFast.py               128     44    66%
mteb/abstasks/AbsTaskInstructionRetrieval.py         238    206    13%
mteb/abstasks/AbsTaskMultilabelClassification.py      96      2    98%
mteb/abstasks/AbsTaskPairClassification.py            28      0   100%
mteb/abstasks/AbsTaskReranking.py                     17      0   100%
mteb/abstasks/AbsTaskRetrieval.py                    193     48    75%
mteb/abstasks/AbsTaskSTS.py                           25      0   100%
mteb/abstasks/AbsTaskSpeedTask.py                     62     39    37%
mteb/abstasks/AbsTaskSummarization.py                 24      0   100%
mteb/abstasks/MultiSubsetLoader.py                    27     21    22%
mteb/abstasks/MultilingualTask.py                     12      1    92%
mteb/abstasks/TaskMetadata.py                         98      4    96%
mteb/abstasks/__init__.py                             15      0   100%
mteb/abstasks/stratification.py                       93     79    15%
----------------------------------------------------------------------
TOTAL                                               1297    480    63%
```

**Comment by KennethEnevoldsen** [comment]
I have added a test for the subset loader. In general a low coverage is not bad, but I do agree that it would be great to expand the test coverage in meaningful way.

I have added a command:

`mteb test-with-coverage` 

as well as added a few ignores (notably for mteb/tasks/*.

I also did a few refactors of the test to speed it up.


```
---------- coverage: platform darwin, python 3.8.19-final-0 ----------
Name                                                          Stmts   Miss  Cover   Missing
-------------------------------------------------------------------------------------------
mteb/MTEBResults.py                                             132     17    87%   113, 120, 122, 124, 129-130, 137, 140-141, 155-158, 175-177, 267
mteb/__init__.py                                                  8      0   100%
mteb/abstasks/AbsTask.py                                        102      6    94%   98, 114, 152-162
mteb/abstasks/AbsTaskBitextMining.py                             35      5    86%   31, 37, 52, 70-71
mteb/abstasks/AbsTaskClassification.py                           69      4    94%   72, 116, 125, 143
mteb/abstasks/AbsTaskClustering.py                               26      0   100%
mteb/abstasks/AbsTaskClusteringFast.py                          128     45    65%   43, 54, 114, 127, 135, 139, 188-209, 218-249, 258
mteb/abstasks/AbsTaskInstructionRetrieval.py                    238    206    13%   38-68, 78-121, 130-150, 153-185, 188-215, 251, 254-325, 328-515, 528-596, 599-606, 609-622, 631-641, 647-660
mteb/abstasks/AbsTaskMultilabelClassification.py                 96      2    98%   82, 95
mteb/abstasks/AbsTaskPairClassification.py                       28      0   100%
mteb/abstasks/AbsTaskReranking.py                                17      0   100%
mteb/abstasks/AbsTaskRetrieval.py                               193     48    75%   47-60, 66-72, 80-83, 111-120, 131, 158, 180, 268, 293, 341-369, 381-382, 412, 415
mteb/abstasks/AbsTaskSTS.py                                      25      0   100%
mteb/abstasks/AbsTaskSpeedTask.py                                62     40    35%   33-39, 42-45, 49-76, 81-98, 101
mteb/abstasks/AbsTaskSummarization.py                            24      0   100%
mteb/abstasks/MultiSubsetLoader.py                               27      5    81%   10, 16, 43-45
mteb/abstasks/MultilingualTask.py                                12      0   100%
mteb/abstasks/TaskMetadata.py                                    98      4    96%   208, 247, 251, 255
mteb/abstasks/__init__.py                                        15      0   100%
mteb/abstasks/stratification.py                                  93     10    89%   99-107, 190, 297
mteb/benchmarks.py                                               21      1    95%   21
mteb/cli.py                                                     101      9    91%   98, 100, 102, 236-237, 265, 346-360
mteb/encoder_interface.py                                        20      5    75%   33, 61, 80, 101, 117
mteb/evaluation/LangMapping.py                                    2      0   100%
mteb/evaluation/MTEB.py                                         213     42    80%   70, 84, 89, 94, 100, 112, 120, 125-126, 132-137, 145, 204-208, 243-246, 336-350, 383-395, 411-417, 436
mteb/evaluation/__init__.py                                       2      0   100%
mteb/evaluation/evaluators/BitextMiningEvaluator.py              75     11    85%   58-67, 125, 127, 131
mteb/evaluation/evaluators/ClassificationEvaluator.py           219    160    27%   27, 43-56, 59-84, 100-113, 116-155, 171-185, 188-238, 247-261, 270-282, 291-303, 321-324
mteb/evaluation/evaluators/ClusteringEvaluator.py                29      2    93%   30-31
mteb/evaluation/evaluators/Evaluator.py                          14      0   100%
mteb/evaluation/evaluators/InstructionRetrievalEvaluator.py      11      5    55%   20-28
mteb/evaluation/evaluators/PairClassificationEvaluator.py       114      9    92%   50-52, 65-70, 99-103
mteb/evaluation/evaluators/RerankingEvaluator.py                214     79    63%   49, 61, 107-119, 130-131, 147-165, 183, 229, 248-266, 292-297, 303-337, 342-364, 367-375, 390-400
mteb/evaluation/evaluators/RetrievalEvaluator.py                264     45    83%   85, 94, 142, 155, 203-215, 297, 314-321, 324-326, 345, 354-359, 382, 385, 400, 416, 420, 430-437, 442-444, 452, 481-484, 503, 588-601
mteb/evaluation/evaluators/STSEvaluator.py                       46      5    89%   34-36, 75-79
mteb/evaluation/evaluators/SummarizationEvaluator.py             72      6    92%   37-40, 118-122
mteb/evaluation/evaluators/__init__.py                            9      0   100%
mteb/evaluation/evaluators/model_encode.py                       17      0   100%
mteb/evaluation/evaluators/utils.py                             194     89    54%   30, 51, 89-91, 105-137, 146-177, 186-222, 234, 283-294, 298-334
mteb/languages.py                                                47      0   100%
mteb/logging.py                                                  11     11     0%   1-28
mteb/model_meta.py                                               49      2    96%   38, 99
mteb/models/__init__.py                                          43      3    93%   43-44, 62
mteb/models/bge_models.py                                        24     10    58%   17-18, 21, 30, 33-38, 46-48
mteb/models/e5_instruct.py                                       94     54    43%   30-34, 47-54, 59-73, 78, 84-87, 98-114, 121-139, 142, 154-157, 168-173, 181, 189-210, 219
mteb/models/e5_models.py                                         34      9    74%   131, 140, 149-151, 160-163
mteb/models/gritlm.py                                            14      6    57%   11-18
mteb/models/instructions.py                                      11      7    36%   127-136
mteb/models/mxbai_models.py                                      24     10    58%   17-18, 21, 30, 33-38, 46-48
mteb/models/openai_models.py                                     32     14    56%   18-23, 26-34, 44, 49-50, 53
mteb/models/ru_sentence_models.py                                 5      0   100%
mteb/models/sentence_transformers_models.py                       6      0   100%
mteb/models/text_formatting_utils.py                              7      5    29%   7-17
mteb/models/voyage_models.py                                     71     49    31%   15-38, 42-62, 74-80, 85, 90, 99-100, 108-129
mteb/overview.py                                                 93     10    89%   46, 53, 101-102, 116, 129-132, 203
mteb/requires_package.py                                          8      5    38%   5-6, 10-12
-------------------------------------------------------------------------------------------
TOTAL                                                          3638   1055    71%

===================================================================================================== slowest 5 durations =====================================================================================================
18.12s call     tests/test_mteb_rerank.py::test_reranker_same_ndcg1
18.11s call     tests/test_mteb.py::test_mteb_with_instructions[Banking77Classification]
16.54s call     tests/test_mteb.py::test_mteb_task[average_word_embeddings_levy_dependency-Banking77Classification]
15.95s call     tests/test_mteb.py::test_mteb_with_instructions[SciDocsRR]
14.47s call     tests/test_mteb_rerank.py::test_mteb_rerank
```

**Comment by KennethEnevoldsen** [comment]
Due to the failing tests I also added the fix to #930 as well as added test to ensure that trust_remote_code=True is not set for future datasets.

**Review by Muennighoff — COMMENTED** [review]
Looks great! Should we open an issue for gradually converting those old datasets? Could be something nice for new contributors

**Comment by Muennighoff** [comment]
Should we merge this? I think the GPUtil change in this PR is important cuz it's breaking people's code atm

**Pull request merged**
