### PR TITLE
Integrate COIR into MTEB

### PR DESCRIPTION
**Pull request by monikernemo**
## Checklist

- [x] Run tests locally to make sure nothing is broken using `make test`. 
- [x] Run the formatter to format the code using `make lint`. 

### Adding datasets checklist

**Reason for dataset addition**: ... 

- [x] I have run the following models on the task (adding the results to the pr). These can be run using the `mteb -m {model_name} -t {task_name}` command.
  - [x] `sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2`
  - [x] `intfloat/multilingual-e5-small`
- [x] I have checked that the performance is neither trivial (both models gain close to perfect scores) nor random (both models gain close to random scores).
- [ ] If the dataset is too big (e.g. >2048 examples), considering using `self.stratified_subsampling() under dataset_transform()`
- [x] I have filled out the metadata object in the dataset file (find documentation on it [here](https://github.com/embeddings-benchmark/mteb/blob/main/docs/adding_a_dataset.md#2-creating-the-metadata-object)).
- [x] Run tests locally to make sure nothing is broken using `make test`. 
- [x] Run the formatter to format the code using `make lint`.

### CODE REVIEW

**Review by KennethEnevoldsen — COMMENTED** [review]
Thanks for this PR it is very much appreciated

How does this implementation compares in terms of score to that of  #1130. From my reading it seems like most of the differences is caused by the loading (we had a similar discussion in the previous PR). Essentially we would prefer if datasets used for mteb only reside within a singular hf dataset (to ensure the versioning).

I also see that you introduce a couple of new classes. I do believe that we can avoid those if we standardize on the loading format. In fact I could imagine this would get you quite close to #1130. Do let me know if that is not the caes though

It also seems like the descriptive stats are not filled out. There is a function for that [here](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/abstasks/AbsTaskRetrieval.py#L389)

Besides that metadata looks very reasonable and I assume you have checked that metrics match.

We should also be sure to add the benchmark to benchmark.py. 

@Samoed if you have the time to look at this implementation as well.

**Comment by Samoed** [comment]
I've looked in the implementation and it's very similar as I had in the beginning.

**Comment by monikernemo** [comment]
@KennethEnevoldsen - I opened this PR (right) before #1130 was merged. @archersama and I intended this to be our attempt, as authors of CoIR, to integrate CoIR into MTEB. However, seeing #1130 was merged, I think we will just work on changing #1130 as mentioned by your comments. Functionally they should be equivalent, but we will be changing some of the HF datasets repos in #1130 to our own HF dataset repos for future maintenance purposes.

**Comment by Samoed** [comment]
I wrote a script that transforms your datasets in one. Maybe will be helpful.

```python
import datasets
from tqdm.auto import tqdm

datasets_list = [
    # "apps",
    # "codetrans-contest",
    # "codetrans-dl",
    # "cosqa",
    # "stackoverflow-qa",
    # "synthetic-text2sql",
    "codefeedback-mt",
    "codefeedback-st",
]

for dataset_name in tqdm(datasets_list):
    qrels = datasets.load_dataset(f"CoIR-Retrieval/{dataset_name}-qrels")
    corpus = datasets.load_dataset(
        f"CoIR-Retrieval/{dataset_name}-queries-corpus", split="corpus"
    )
    queries = datasets.load_dataset(
        f"CoIR-Retrieval/{dataset_name}-queries-corpus", split="queries"
    )
    qrels = qrels.rename_columns(
        {
            "query_id": "query-id",
            "corpus_id": "corpus-id",
        }
    )
    qrels.push_to_hub(f"mteb/{dataset_name}")
    corpus.push_to_hub(f"mteb/{dataset_name}", config_name="corpus")
    queries.push_to_hub(f"mteb/{dataset_name}", config_name="queries")

splits = ["python", "javascript", "go", "ruby", "java", "php"]
for split in tqdm(splits):
    qrels = datasets.load_dataset(f"CoIR-Retrieval/CodeSearchNet-ccr-{split}-qrels")
    corpus = datasets.load_dataset(
        f"CoIR-Retrieval/CodeSearchNet-ccr-{split}-queries-corpus", split="corpus"
    )
    queries = datasets.load_dataset(
        f"CoIR-Retrieval/CodeSearchNet-ccr-{split}-queries-corpus", split="queries"
    )
    qrels = qrels.rename_columns(
        {
            "query_id": "query-id",
            "corpus_id": "corpus-id",
        }
    )
    corpus.push_to_hub("mteb/CodeSearchNet-ccr", config_name=f"{split}-corpus")
    queries.push_to_hub("mteb/CodeSearchNet-ccr", config_name=f"{split}-queries")
    qrels.push_to_hub("mteb/CodeSearchNet-ccr", config_name=f"{split}-qrels")
```

**Comment by KennethEnevoldsen** [comment]
> we will be changing some of the HF datasets repos in https://github.com/embeddings-benchmark/mteb/pull/1130 to our own HF dataset repos for future maintenance purposes. As such, I will close this PR.

That is perfectly fine. You might take a look at this issue https://github.com/embeddings-benchmark/mteb/issues/1090

**Pull request closed without merging**
