### PR TITLE
fix: add check_label_distribution for ClusteringFast

### PR DESCRIPTION
**Pull request by isaac-chung**
Addresses #834

### CODE REVIEW

**Comment by KennethEnevoldsen** [comment]
thanks, @isaac-chung, seems like most (all?) datasets pass the checks. Probably my worry was unwarranted

**Comment by isaac-chung** [comment]
@KennethEnevoldsen no worries, it's good that we checked 👍 

We could merge this just to point back to it if the topic comes up again. What do you think?

**Comment by isaac-chung** [comment]
Added points as well - see if that makes sense?

**Comment by KennethEnevoldsen** [comment]
Looks great! - setting automerge

**Pull request merged**
