### PR TITLE
add Indic language identification dataset in Classification category

### PR DESCRIPTION
**Pull request by jaygala24**
## Checklist for adding MMTEB dataset

Reason for dataset addition:

- [x] I have tested that the dataset runs with the `mteb` package.
- [x] I have run the following models on the task (adding the results to the pr). These can be run using the `mteb run -m {model_name} -t {task_name}` command.
  - [x] `sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2`
  - [x] `intfloat/multilingual-e5-small`
- [x] I have checked that the performance is neither trivial (both models gain close to perfect scores) nor random (both models gain close to random scores).
- [x] If the dataset is too big (e.g. >2048 examples), considering using `self.stratified_subsampling() under dataset_transform()`
- [x] I have filled out the metadata object in the dataset file (find documentation on it [here](https://github.com/embeddings-benchmark/mteb/blob/main/docs/adding_a_dataset.md#2-creating-the-metadata-object)).
- [x] Run tests locally to make sure nothing is broken using `make test`. 
- [x] Run the formatter to format the code using `make lint`. 
- [ ] I have added points for my submission to the [points folder](https://github.com/embeddings-benchmark/mteb/blob/main/docs/mmteb/points.md) using the PR number as the filename (e.g. `438.jsonl`).

### CODE REVIEW

**Comment by jaygala24** [comment]
Add language identification dataset spanning 22 Indic languages. Out of 22 Indic languages, 13 languages overlap with other datasets in classification and 9 languages are new ones. These new languages include 'gom', 'kas', 'mni', 'npi', 'snd', 'sat', 'san', 'doi', 'mai'.

Points Summary:
- This dataset = 2 pts
- Any new language not covered previously in classification = 4 pts x 9 languages

Total points = 2 + 4 x 9 = 38 pts

Team:
- Diganta Mista (@digantamisra98) - MILA
- Jay Gala (@jaygala24) - AI4Bharat

**Review by isaac-chung — COMMENTED** [review]
Great job! Feel free to add the points.

**Comment by jaygala24** [comment]
> Great job! Feel free to add the points.

@isaac-chung I have added the points for the dataset addition and PR review.

**Review by isaac-chung — APPROVED** [review]
Looks good! Thanks again for your contributions.

**Pull request merged**
