### PR TITLE
fix: Fix broken clustering tasks

### PR DESCRIPTION
**Pull request by KennethEnevoldsen**
Fix clustering tasks using Imenes fix

## Checklist

- [ ] Run tests locally to make sure nothing is broken using `make test`. 
- [ ] Run the formatter to format the code using `make lint`.

### CODE REVIEW

**Review by imenelydiaker — APPROVED** [review]
Look good!

Is it a good Idea to make the subsampling function more robust by choosing the number of samples to min(size of dataset, N_SAMPLES) ?

It can be done later, this fix is already great! Thanks Kenneth!

**Comment by KennethEnevoldsen** [comment]
I will add that in as well!

**Comment by imenelydiaker** [comment]
> I will add that in as well! - I suppose we don't really need to subsample at all if that is the case

Yeah true, it's just that the subsampling function can be applied to all available subsets and splits. Some times for a split you can have multiple subsets which some of do not need subsampling (that's what happenned with MLSUM). It's either adding a condition on the length of the dataset before calling the subsampling function or making subsampling_fn handle it by default. But no rush on this, I'm not sure we have the same problem elsewhere.

**Review by imenelydiaker — APPROVED** [review]
LGTM! Thanks 🚀

**Comment by KennethEnevoldsen** [comment]
@imenelydiaker added the downsampling fix. I also found another error due to python 3.8 and a an odd numpy data type.

**Comment by imenelydiaker** [comment]
Perfect, you can merge this PR 😊

**Pull request merged**
