### PR TITLE
Fix create_meta function in cli.py

### PR DESCRIPTION
**Pull request by lbourdois**
Hello,

I followed the instructions provided in [https://github.com/embeddings-benchmark/mteb/blob/main/docs/adding_a_model.md](https://github.com/embeddings-benchmark/mteb/blob/main/docs/adding_a_model.md).
It turns out that at step "**3. Add the frontmatter to model repository**", when copying the metadata generated in the README.md, Hugging Face returns the following error:
image

After some investigation, I realized that this was because "s" was missing for "metrics" as well as a "-" before the "type:" contained in "metrics". 
By adding them, everything works locally. So I'm taking the liberty of opening this PR to avoid this problem for others.

Have a nice day :)

### CODE REVIEW

**Review by KennethEnevoldsen — APPROVED** [review]

**Comment by KennethEnevoldsen** [comment]
Wonderful thanks for the PR

**Comment by henilp105** [comment]
@lbourdois Thanks for the PR, The tests are failing due to the `tests/test_cli.py` , to resolve them you would have to change line 11 in `tests/create_meta/model_card.md` and `tests/create_meta/model_card_gold.md`  with `metrics` .  (extra `s`)

**Comment by lbourdois** [comment]
Thanks for the tip @henilp105, it's been propagated

**Review by henilp105 — COMMENTED** [review]
Thanks @lbourdois , just run the `make lint`  and then push a commit , so that it could be merged.

**Comment by KennethEnevoldsen** [comment]
Pushing and linting in main

**Comment by lbourdois** [comment]
Sorry I've been off for the last few days. Glad you could manage without me 🤗

**Pull request merged**
