### PR TITLE
Add CLEVR and SciMMIR Image-Text Understanding tasks

### PR DESCRIPTION
**Pull request by imenelydiaker**
- [x] I have filled out the metadata object in the dataset file (find documentation on it [here](https://github.com/embeddings-benchmark/mteb/blob/main/docs/adding_a_dataset.md#2-creating-the-metadata-object)).
- [x] Run tests locally to make sure nothing is broken using `make test`. 
- [x] Run the formatter to format the code using `make lint`.

### CODE REVIEW

**Comment by gowitheflow-1998** [comment]
nice thanks! For CLEVR, can you add the [count task](https://huggingface.co/datasets/clip-benchmark/wds_vtab-clevr_count_all) as well? Also both count and distance are worth adding linear probing.

Didn't realize SciMMIR can be a zero-shot classification as well (it is a retrieval task with image-caption) but I think is quite cool to add the zero-shot classification as you do here! The results indicate this is still a task that's not too easy so worth keeping. I can take care of the retrieval version later unless you have the bandwidth? I have just fixed image memory issues for all retrieval so it should be runnable with it as well.

**Comment by gowitheflow-1998** [comment]
> I'm not aware of how much work it requires to add it as a retieval task. Would it require building a corpus and queries? I'll have a look at it and keep you posted, we'll add it in another PR anyway.

yeah we'll need to build corpus, queries and qrels like other retrieval tasks. No worries. lmk!

**Comment by imenelydiaker** [comment]
> > I'm not aware of how much work it requires to add it as a retieval task. Would it require building a corpus and queries? I'll have a look at it and keep you posted, we'll add it in another PR anyway.
> 
> yeah we'll need to build corpus, queries and qrels like other retrieval tasks. No worries. lmk!

Added CLEVR count task. I think we'd do SciMMIR retrieval tasks in another PR (Text2Image and Image2Text). This one is ready 🙂

**Review by gowitheflow-1998 — APPROVED** [review]

**Comment by gowitheflow-1998** [comment]
yeah looks nice! CLEVR's linear probing can be in another pr as well.

**Pull request merged**
