### PR TITLE
Leaderboard: Fixed code benchmarks

### PR DESCRIPTION
**Pull request by x-tabdeveloping**
Along with updating the selected values, I also update the choices in the dropdowns.

### CODE REVIEW

**Comment by x-tabdeveloping** [comment]
@Muennighoff I added a fix for the bug you encountered. I think the problem lied in Jina not having an incorrect number of parameters in the metadata though (572K instead of 572M)

**Comment by x-tabdeveloping** [comment]
Actually, I didn't fix it, I encountered yet another bug in Gradio I have to work around :)))))))

**Review by isaac-chung — APPROVED** [review]
Looks good. If you could attach screenshots of the changes in the UI, that'd be great as well :)

**Review by KennethEnevoldsen — APPROVED** [review]

**Comment by KennethEnevoldsen** [comment]
This looks good so far @x-tabdeveloping, let us go through it in person today to get most of the kinks removed (I have a meeting at 15) and figure out what is needed before a final review among colaborators

**Comment by x-tabdeveloping** [comment]
@isaac-chung the UI largely remained the same, no significant changes there

**Pull request merged**
