### PR TITLE
[mieb] Fix vlm2vec

### LINKED ISSUE #1377: [mieb] TIGER-Lab/VLM2Vec-LoRA fails
```
INFO:mteb.cli:Running with parameters: Namespace(model='TIGER-Lab/VLM2Vec-LoRA', task_types=None, categories=None, tasks=['BLINKIT2IRetrieval'], languages=None, benchmarks=None, device=None, output_folder='/data/niklas/mieb/results-mieb-final', verbosity=2, co2_tracker=True, eval_splits=None, model_revision=None, batch_size=4, overwrite=False, save_predictions=False, func=<function run at 0x7feee99e23b0>)
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
Loading checkpoint shards:  50%|█████     | 1/2 [00:04<00:04,  4.68s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:07<00:00,  3.42s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:07<00:00,  3.61s/it]
/env/lib/conda/gritkto4/lib/python3.10/site-packages/transformers/models/auto/image_processing_auto.py:520: FutureWarning: The image_processor_class argument is deprecated and will be removed in v4.42. Please use `slow_image_processor_class`, or `fast_image_processor_class` instead
  warnings.warn(
INFO:mteb.evaluation.MTEB:

## Evaluating 1 tasks:
─────────────────────────────── Selected tasks  ────────────────────────────────
Any2AnyRetrieval
    - BLINKIT2IRetrieval, it2i


INFO:mteb.evaluation.MTEB:

********************** Evaluating BLINKIT2IRetrieval **********************
INFO:mteb.evaluation.MTEB:Loading dataset for BLINKIT2IRetrieval
INFO:mteb.abstasks.Image.AbsTaskAny2AnyRetrieval:Loading Corpus...
INFO:mteb.abstasks.Image.AbsTaskAny2AnyRetrieval:Loaded 804 TEST Documents.
INFO:mteb.abstasks.Image.AbsTaskAny2AnyRetrieval:Doc Example: {'id': 'val_Art_Style_1_2', 'modality': 'image', 'image': <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1382x1718 at 0x7FF21EA29540>}
INFO:mteb.abstasks.Image.AbsTaskAny2AnyRetrieval:Loading Queries...

Map:   0%|          | 0/402 [00:00<?, ? examples/s]
Map: 100%|██████████| 402/402 [00:00<00:00, 43397.17 examples/s]
INFO:mteb.abstasks.Image.AbsTaskAny2AnyRetrieval:Loaded 402 TEST Queries.
INFO:mteb.abstasks.Image.AbsTaskAny2AnyRetrieval:Query Example: {'id': 'val_Art_Style_1_1', 'modality': 'image,text', 'text': 'Which image shares the same style as the reference image?', 'image': <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1382x2057 at 0x7FF21E967A60>}
INFO:mteb.abstasks.Image.AbsTaskAny2AnyRetrieval:Subset: default
INFO:mteb.evaluation.evaluators.Image.Any2AnyRetrievalEvaluator:Encoding Queries.

  0%|          | 0/101 [00:00<?, ?it/s]
  0%|          | 0/101 [00:00<?, ?it/s]
ERROR:mteb.evaluation.MTEB:Error while evaluating BLINKIT2IRetrieval: expected mat1 and mat2 to have the same dtype, but got: c10::BFloat16 != float
Traceback (most recent call last):
  File "/env/lib/conda/gritkto4/bin/mteb", line 8, in <module>
    sys.exit(main())
  File "/data/niklas/mieb/mteb/mteb/cli.py", line 387, in main
    args.func(args)
  File "/data/niklas/mieb/mteb/mteb/cli.py", line 145, in run
    eval.run(
  File "/data/niklas/mieb/mteb/mteb/evaluation/MTEB.py", line 464, in run
    raise e
  File "/data/niklas/mieb/mteb/mteb/evaluation/MTEB.py", line 412, in run
    results, tick, tock = self._run_eval(
  File "/data/niklas/mieb/mteb/mteb/evaluation/MTEB.py", line 300, in _run_eval
    results = task.evaluate(
  File "/data/niklas/mieb/mteb/mteb/abstasks/Image/AbsTaskAny2AnyRetrieval.py", line 269, in evaluate
    scores[hf_subset] = self._evaluate_subset(
  File "/data/niklas/mieb/mteb/mteb/abstasks/Image/AbsTaskAny2AnyRetrieval.py", line 278, in _evaluate_subset
    results = retriever(corpus, queries)
  File "/data/niklas/mieb/mteb/mteb/evaluation/evaluators/Image/Any2AnyRetrievalEvaluator.py", line 290, in __call__
    return self.retriever.search(
  File "/data/niklas/mieb/mteb/mteb/evaluation/evaluators/Image/Any2AnyRetrievalEvaluator.py", line 144, in search
    query_embeddings = self.model.get_fused_embeddings(
  File "/data/niklas/mieb/mteb/mteb/models/vlm2vec_models.py", line 243, in get_fused_embeddings
    text_embeddings = self.get_text_embeddings(texts, batch_size)
  File "/data/niklas/mieb/mteb/mteb/models/vlm2vec_models.py", line 223, in get_text_embeddings
    text_outputs = self.encode_input(inputs)
  File "/data/niklas/mieb/mteb/mteb/models/vlm2vec_models.py", line 91, in encode_input
    hidden_states = self.mdl(**input, return_dict=True, output_hidden_states=True)
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/huggingface/modules/transformers_modules/microsoft/Phi-3.5-vision-instruct/4a0d683eba9f1d0cbfb6151705d1ee73c25a80ca/modeling_phi3_v.py", line 1603, in forward
    outputs = self.model(
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/huggingface/modules/transformers_modules/microsoft/Phi-3.5-vision-instruct/4a0d683eba9f1d0cbfb6151705d1ee73c25a80ca/modeling_phi3_v.py", line 1479, in forward
    layer_outputs = decoder_layer(
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/huggingface/modules/transformers_modules/microsoft/Phi-3.5-vision-instruct/4a0d683eba9f1d0cbfb6151705d1ee73c25a80ca/modeling_phi3_v.py", line 1177, in forward
    attn_outputs, self_attn_weights, present_key_value = self.self_attn(
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/huggingface/modules/transformers_modules/microsoft/Phi-3.5-vision-instruct/4a0d683eba9f1d0cbfb6151705d1ee73c25a80ca/modeling_phi3_v.py", line 765, in forward
    qkv = self.qkv_proj(hidden_states)
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 117, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected mat1 and mat2 to have the same dtype, but got: c10::BFloat16 != float

```

### PR DESCRIPTION
**Pull request by isaac-chung**
Fixes #1377 

- Fix erroneous logic in `get_fused_embeddings`
- Fix returned embeddings dtypes to `torch.float32`

CC @Muennighoff 

## Checklist

- [x] Run tests locally to make sure nothing is broken using `make test`. 
- [x] Run the formatter to format the code using `make lint`.

### CODE REVIEW

**Review by gowitheflow-1998 — APPROVED** [review]

**Comment by gowitheflow-1998** [comment]
thanks for the fix! Looks like the previous logic will affect tasks that require interleaved encodings, where only the text part was encoded? I'll collect a list of datasets that need to be rerun. cc @Muennighoff

**Comment by Muennighoff** [comment]
> I'll collect a list of datasets that need to be rerun.

If it is only the LoRA model then it is fine as I haven't run anything for that yet due to the error
https://github.com/embeddings-benchmark/tmp/tree/master/TIGER-Lab__VLM2Vec-LoRA/7403b6327958071c1e33c822c7453adadccc7298

**Comment by gowitheflow-1998** [comment]
> If it is only the LoRA model then it is fine as I haven't run anything for that yet due to the error

Yes, after double-checking, it's only the LoRA model so no need for rerun! The previous `get_fused_embedding` encodes texts, images and both three times but still only returned the multimodal embeddings, so the current results for the Full model should be correct, although it was slow before the fix

**Comment by Muennighoff** [comment]
Still getting an error with this model; verified that I have the changes from this PR. Are you using the same versions as me?
```
    img_features = self.get_img_features(pixel_values.flatten(0, 1)).reshape(                       [42/1924]
  File "/data/huggingface/modules/transformers_modules/microsoft/Phi-3.5-vision-instruct/4a0d683eba9f1d0cbfb6
151705d1ee73c25a80ca/modeling_phi3_v.py", line 212, in get_img_features                                      
    img_processor_output = self.img_processor(img_embeds, output_hidden_states=True)                         
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrap
ped_call_impl                                                                                                
    return self._call_impl(*args, **kwargs)                                                                  
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call
_impl                                                                                                        
    return forward_call(*args, **kwargs)                                                                     
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line
 1171, in forward                                                                                            
    return self.vision_model(                                                                                
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrap
ped_call_impl                                                                                                
    return self._call_impl(*args, **kwargs)                                                                  
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call
_impl                                                                                                        
    return forward_call(*args, **kwargs)                                                                     
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line
 1097, in forward                                                                                            
    encoder_outputs = self.encoder(                                                                          
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrap
ped_call_impl                                                                                                
    return self._call_impl(*args, **kwargs)                                                                  
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call
_impl                                                                                                        
    return forward_call(*args, **kwargs)                                                                     
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line
 877, in forward                                                                                             
    layer_outputs = encoder_layer(                                                                           
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrap
ped_call_impl                                                                                                
    return self._call_impl(*args, **kwargs)                                                                  
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call
_impl                                                                                                        
    return forward_call(*args, **kwargs)                                                                     
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line
 608, in forward                                                                                             
    hidden_states, attn_weights = self.self_attn(                                                            
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrap
ped_call_impl                                                                                                    return self._call_impl(*args, **kwargs)                                                                  
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call
    return self._call_impl(*args, **kwargs)
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/huggingface/modules/transformers_modules/microsoft/Phi-3.5-vision-instruct/4a0d683eba9f1d0cbfb6151705d1ee73c25a80ca/modeling_phi3_v.py", line 101, in forward
    query_states = self.q_proj(hidden_states).reshape(bsz, tgt_len, self.num_heads, self.head_dim)
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 117, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: self and mat2 must have the same dtype, but got BFloat16 and Float
(/env/lib/conda/gritkto4) niklas@dojo-a3-ghpc-61:/data/niklas/mieb/mteb$ pip show torch
Name: torch
Version: 2.4.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /data/env/lib/conda/gritkto4/lib/python3.10/site-packages
Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-nccl-cu12, nvidia-nvtx-cu12, sympy, triton, typing-extensions
Required-by: accelerate, fairscale, FlagEmbedding, flash-attn, mteb, open_clip_torch, peft, salesforce-lavis, sentence-transformers, timm, torchaudio, torchvision, xformers
(/env/lib/conda/gritkto4) niklas@dojo-a3-ghpc-61:/data/niklas/mieb/mteb$ pip show transformers
Name: transformers
Version: 4.46.2
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: /data/env/lib/conda/gritkto4/lib/python3.10/site-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
Required-by: FlagEmbedding, peft, salesforce-lavis, sentence-transformers
```

**Comment by isaac-chung** [comment]
Mine is this:

```
~/isaac/work/mteb$ pip show torch
Name: torch
Version: 2.5.1+cu124
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3-Clause
Location: /home/ubuntu/miniconda3/lib/python3.11/site-packages
Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-nccl-cu12, nvidia-nvjitlink-cu12, nvidia-nvtx-cu12, sympy, triton, typing-extensions
Required-by: accelerate, FlagEmbedding, flash-attn, lm_eval, mteb, open_clip_torch, peft, sentence-transformers, thop, timm, torchaudio, torchvision, ultralytics, xformers
~/isaac/work/mteb$ pip show transformers
Name: transformers
Version: 4.45.2
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: /home/ubuntu/miniconda3/lib/python3.11/site-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
Required-by: FlagEmbedding, lm_eval, peft, sentence-transformers
```

**Comment by Muennighoff** [comment]
Hm yeah I cannot upgrade torch on my system unfortunately

**Comment by isaac-chung** [comment]
I downgraded torch to `2.4.0` and run `mteb run -m TIGER-Lab/VLM2Vec-LoRA -t BLINKIT2IRetrieval` successfully on the latest `mieb` branch. 🤔 

<details>

```
$ mteb run -m TIGER-Lab/VLM2Vec-LoRA -t BLINKIT2IRetrieval
2024-11-09 08:37:47.907580: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-11-09 08:37:47.926855: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-11-09 08:37:47.951916: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-11-09 08:37:47.959533: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-09 08:37:47.976096: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-11-09 08:37:48.759659: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
INFO:mteb.cli:Running with parameters: Namespace(model='TIGER-Lab/VLM2Vec-LoRA', task_types=None, categories=None, tasks=['BLINKIT2IRetrieval'], languages=None, benchmarks=None, device=None, output_folder='results', verbosity=2, co2_tracker=False, eval_splits=None, model_revision=None, batch_size=None, overwrite=False, save_predictions=False, func=<function run at 0x7feabc8867a0>)
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  3.38it/s]
/home/ubuntu/miniconda3/lib/python3.11/site-packages/peft/utils/save_and_load.py:328: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  adapters_weights = torch.load(filename, map_location=torch.device(device))
/home/ubuntu/miniconda3/lib/python3.11/site-packages/transformers/models/auto/image_processing_auto.py:517: FutureWarning: The image_processor_class argument is deprecated and will be removed in v4.42. Please use `slow_image_processor_class`, or `fast_image_processor_class` instead
  warnings.warn(
INFO:mteb.evaluation.MTEB:

## Evaluating 1 tasks:
──────────────────────────────────────────────────────────────────────────────────────────── Selected tasks  ────────────────────────────────────────────────────────────────────────────────────────────
Any2AnyRetrieval
    - BLINKIT2IRetrieval, it2i


INFO:mteb.evaluation.MTEB:

********************** Evaluating BLINKIT2IRetrieval **********************
INFO:mteb.evaluation.MTEB:Loading dataset for BLINKIT2IRetrieval
INFO:mteb.abstasks.Image.AbsTaskAny2AnyRetrieval:Loading Corpus...
INFO:mteb.abstasks.Image.AbsTaskAny2AnyRetrieval:Loaded 804 TEST Documents.
INFO:mteb.abstasks.Image.AbsTaskAny2AnyRetrieval:Doc Example: {'id': 'val_Art_Style_1_2', 'modality': 'image', 'image': <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1382x1718 at 0x7FEA78E08550>}
INFO:mteb.abstasks.Image.AbsTaskAny2AnyRetrieval:Loading Queries...
Map: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 402/402 [00:00<00:00, 20673.50 examples/s]
INFO:mteb.abstasks.Image.AbsTaskAny2AnyRetrieval:Loaded 402 TEST Queries.
INFO:mteb.abstasks.Image.AbsTaskAny2AnyRetrieval:Query Example: {'id': 'val_Art_Style_1_1', 'modality': 'image,text', 'text': 'Which image shares the same style as the reference image?', 'image': <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1382x2057 at 0x7FEA78E511D0>}
INFO:mteb.abstasks.Image.AbsTaskAny2AnyRetrieval:Subset: default
INFO:mteb.evaluation.evaluators.Image.Any2AnyRetrievalEvaluator:Encoding Queries.
INFO:mteb.evaluation.evaluators.Image.Any2AnyRetrievalEvaluator:Preparing Corpus...
INFO:mteb.evaluation.evaluators.Image.Any2AnyRetrievalEvaluator:Encoding Corpus in batches... Warning: This might take a while!
INFO:mteb.evaluation.evaluators.Image.Any2AnyRetrievalEvaluator:Scoring Function: Cosine Similarity (cos_sim)
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [02:17<00:00,  1.46it/s]
INFO:mteb.abstasks.Image.AbsTaskAny2AnyRetrieval:Time taken to retrieve: 221.55 seconds
INFO:mteb.evaluation.MTEB:Evaluation for BLINKIT2IRetrieval on test took 222.04 seconds
INFO:mteb.evaluation.MTEB:Scores: {'default': {'ndcg_at_1': 0.33333, 'ndcg_at_3': 0.44415, 'ndcg_at_5': 0.46706, 'ndcg_at_10': 0.48577, 'ndcg_at_20': 0.50998, 'ndcg_at_100': 0.54132, 'ndcg_at_1000': 0.55475, 'map_at_1': 0.33333, 'map_at_3': 0.41708, 'map_at_5': 0.43002, 'map_at_10': 0.43787, 'map_at_20': 0.44436, 'map_at_100': 0.4485, 'map_at_1000': 0.44917, 'recall_at_1': 0.33333, 'recall_at_3': 0.52239, 'recall_at_5': 0.57711, 'recall_at_10': 0.63433, 'recall_at_20': 0.73134, 'recall_at_100': 0.90299, 'recall_at_1000': 1.0, 'cv_recall_at_1': 0.33333, 'cv_recall_at_3': 0.52239, 'cv_recall_at_5': 0.57711, 'cv_recall_at_10': 0.63433, 'cv_recall_at_20': 0.73134, 'cv_recall_at_100': 0.90299, 'cv_recall_at_1000': 1.0, 'precision_at_1': 0.33333, 'precision_at_3': 0.17413, 'precision_at_5': 0.11542, 'precision_at_10': 0.06343, 'precision_at_20': 0.03657, 'precision_at_100': 0.00903, 'precision_at_1000': 0.001, 'mrr_at_1': 0.3333333333333333, 'mrr_at_3': 0.4170812603648425, 'mrr_at_5': 0.43001658374792706, 'mrr_at_10': 0.4378711600726526, 'mrr_at_20': 0.4443571342692225, 'mrr_at_100': 0.44849651066042256, 'mrr_at_1000': 0.44916944786380747, 'nauc_ndcg_at_1_max': -0.32353978325607163, 'nauc_ndcg_at_1_std': -0.5583254050202324, 'nauc_ndcg_at_1_diff1': 0.3111193013302067, 'nauc_ndcg_at_3_max': -0.38649159510211695, 'nauc_ndcg_at_3_std': -0.6813347235768292, 'nauc_ndcg_at_3_diff1': 0.25642497582594914, 'nauc_ndcg_at_5_max': -0.4052433373849262, 'nauc_ndcg_at_5_std': -0.7120264320806169, 'nauc_ndcg_at_5_diff1': 0.26924411140706234, 'nauc_ndcg_at_10_max': -0.446152657128688, 'nauc_ndcg_at_10_std': -0.7407766594445515, 'nauc_ndcg_at_10_diff1': 0.25388828330252544, 'nauc_ndcg_at_20_max': -0.47712302574556703, 'nauc_ndcg_at_20_std': -0.7513471135549632, 'nauc_ndcg_at_20_diff1': 0.23991845452569205, 'nauc_ndcg_at_100_max': -0.4454070713174091, 'nauc_ndcg_at_100_std': -0.7157459145512785, 'nauc_ndcg_at_100_diff1': 0.25821864481371587, 'nauc_ndcg_at_1000_max': -0.4279811315465865, 'nauc_ndcg_at_1000_std': -0.7042823784288923, 'nauc_ndcg_at_1000_diff1': 0.25878328495707237, 'nauc_map_at_1_max': -0.32353978325607163, 'nauc_map_at_1_std': -0.5583254050202324, 'nauc_map_at_1_diff1': 0.3111193013302067, 'nauc_map_at_3_max': -0.3716457916265704, 'nauc_map_at_3_std': -0.650872562417237, 'nauc_map_at_3_diff1': 0.26757863785196767, 'nauc_map_at_5_max': -0.3825976120412693, 'nauc_map_at_5_std': -0.6679862730708848, 'nauc_map_at_5_diff1': 0.27425387476190605, 'nauc_map_at_10_max': -0.3992266571249694, 'nauc_map_at_10_std': -0.6794759548428109, 'nauc_map_at_10_diff1': 0.26745220329376024, 'nauc_map_at_20_max': -0.40620578045536115, 'nauc_map_at_20_std': -0.6809151094106392, 'nauc_map_at_20_diff1': 0.26362310391368393, 'nauc_map_at_100_max': -0.40245308588253, 'nauc_map_at_100_std': -0.6765106593253809, 'nauc_map_at_100_diff1': 0.2662583638343377, 'nauc_map_at_1000_max': -0.4016199784018475, 'nauc_map_at_1000_std': -0.6759275618504923, 'nauc_map_at_1000_diff1': 0.26628593394233757, 'nauc_recall_at_1_max': -0.32353978325607163, 'nauc_recall_at_1_std': -0.5583254050202324, 'nauc_recall_at_1_diff1': 0.3111193013302067, 'nauc_recall_at_3_max': -0.42997357405833797, 'nauc_recall_at_3_std': -0.7711849122029174, 'nauc_recall_at_3_diff1': 0.22451261379023907, 'nauc_recall_at_5_max': -0.4764532939353889, 'nauc_recall_at_5_std': -0.8516137414973199, 'nauc_recall_at_5_diff1': 0.2574000895985468, 'nauc_recall_at_10_max': -0.621569338759275, 'nauc_recall_at_10_std': -0.9612960124747869, 'nauc_recall_at_10_diff1': 0.20757330359843257, 'nauc_recall_at_20_max': -0.8341503191231064, 'nauc_recall_at_20_std': -1.0786742923138923, 'nauc_recall_at_20_diff1': 0.12631976359883476, 'nauc_recall_at_100_max': -0.7995412417365978, 'nauc_recall_at_100_std': -0.9483657736837682, 'nauc_recall_at_100_diff1': 0.24608875668422495, 'nauc_recall_at_1000_max': nan, 'nauc_recall_at_1000_std': nan, 'nauc_recall_at_1000_diff1': nan, 'nauc_precision_at_1_max': -0.32353978325607163, 'nauc_precision_at_1_std': -0.5583254050202324, 'nauc_precision_at_1_diff1': 0.3111193013302067, 'nauc_precision_at_3_max': -0.4299735740583386, 'nauc_precision_at_3_std': -0.7711849122029182, 'nauc_precision_at_3_diff1': 0.22451261379023857, 'nauc_precision_at_5_max': -0.47645329393538843, 'nauc_precision_at_5_std': -0.8516137414973198, 'nauc_precision_at_5_diff1': 0.25740008959854693, 'nauc_precision_at_10_max': -0.6215693387592749, 'nauc_precision_at_10_std': -0.9612960124747875, 'nauc_precision_at_10_diff1': 0.20757330359843257, 'nauc_precision_at_20_max': -0.8341503191231064, 'nauc_precision_at_20_std': -1.078674292313892, 'nauc_precision_at_20_diff1': 0.12631976359883446, 'nauc_precision_at_100_max': -0.7995412417365956, 'nauc_precision_at_100_std': -0.9483657736837666, 'nauc_precision_at_100_diff1': 0.24608875668422764, 'nauc_precision_at_1000_max': nan, 'nauc_precision_at_1000_std': nan, 'nauc_precision_at_1000_diff1': nan, 'nauc_cv_recall_at_1_max': -0.32353978325607163, 'nauc_cv_recall_at_1_std': -0.5583254050202324, 'nauc_cv_recall_at_1_diff1': 0.3111193013302067, 'nauc_cv_recall_at_3_max': -0.42997357405833797, 'nauc_cv_recall_at_3_std': -0.7711849122029174, 'nauc_cv_recall_at_3_diff1': 0.22451261379023907, 'nauc_cv_recall_at_5_max': -0.4764532939353889, 'nauc_cv_recall_at_5_std': -0.8516137414973199, 'nauc_cv_recall_at_5_diff1': 0.2574000895985468, 'nauc_cv_recall_at_10_max': -0.621569338759275, 'nauc_cv_recall_at_10_std': -0.9612960124747869, 'nauc_cv_recall_at_10_diff1': 0.20757330359843257, 'nauc_cv_recall_at_20_max': -0.8341503191231064, 'nauc_cv_recall_at_20_std': -1.0786742923138923, 'nauc_cv_recall_at_20_diff1': 0.12631976359883476, 'nauc_cv_recall_at_100_max': -0.7995412417365978, 'nauc_cv_recall_at_100_std': -0.9483657736837682, 'nauc_cv_recall_at_100_diff1': 0.24608875668422495, 'nauc_cv_recall_at_1000_max': nan, 'nauc_cv_recall_at_1000_std': nan, 'nauc_cv_recall_at_1000_diff1': nan, 'nauc_mrr_at_1_max': -0.32353978325607163, 'nauc_mrr_at_1_std': -0.5583254050202324, 'nauc_mrr_at_1_diff1': 0.3111193013302067, 'nauc_mrr_at_3_max': -0.3716457916265704, 'nauc_mrr_at_3_std': -0.650872562417237, 'nauc_mrr_at_3_diff1': 0.26757863785196767, 'nauc_mrr_at_5_max': -0.3825976120412693, 'nauc_mrr_at_5_std': -0.6679862730708848, 'nauc_mrr_at_5_diff1': 0.27425387476190605, 'nauc_mrr_at_10_max': -0.3992266571249694, 'nauc_mrr_at_10_std': -0.6794759548428109, 'nauc_mrr_at_10_diff1': 0.26745220329376024, 'nauc_mrr_at_20_max': -0.40620578045536115, 'nauc_mrr_at_20_std': -0.6809151094106392, 'nauc_mrr_at_20_diff1': 0.26362310391368393, 'nauc_mrr_at_100_max': -0.40245308588253, 'nauc_mrr_at_100_std': -0.6765106593253809, 'nauc_mrr_at_100_diff1': 0.2662583638343377, 'nauc_mrr_at_1000_max': -0.4016199784018475, 'nauc_mrr_at_1000_std': -0.6759275618504923, 'nauc_mrr_at_1000_diff1': 0.26628593394233757, 'main_score': 0.48577}}
```

</details>

**Pull request merged**
