### PR TITLE
docs: Add MTEB(code) dataset

### PR DESCRIPTION
**Pull request by john-b-yang**
* Added `MTEB(code)` to benchmarks
* Updated paper with corresponding info + results table for `MTEB(code)` to Appendix H

### CODE REVIEW

**Review by Muennighoff — APPROVED** [review]
Looks good; For context @john-b-yang added new tables in the paper hence the points!

**Comment by Muennighoff** [comment]
Can you make sure the tests pass? Like the linting etc

**Comment by john-b-yang** [comment]
No problem, just noticed that the `mteb/benchmark/benchmarks.py` isn't quite right - hopefully this commit is good to go

**Comment by KennethEnevoldsen** [comment]
This looks great @john-b-yang, will you add a short description to H1 as well about the creation? Does not need to be very long

**Comment by john-b-yang** [comment]
Ah yes no problem @KennethEnevoldsen! Will do this today!

**Pull request merged**
