### PR TITLE
Leaderboard 2.0: added performance x n_parameters plot + more benchmark info

### PR DESCRIPTION
**Pull request by x-tabdeveloping**
I added an interactive performance vs.  number of parameters plot as the first thing people see when selecting a benchmark. #1396 
I also added some info on the benchmarks to the benchmark description as Niklas requested here: #1317 

Here's a screenshot:
image

I also bumped the Gradio version, as I thought it might fix certain things, but I have two burning problems still, for which I opened respective issues in Gradio (https://github.com/gradio-app/gradio/issues/9938, https://github.com/gradio-app/gradio/issues/9937)

### CODE REVIEW

**Review by isaac-chung — APPROVED** [review]
This is beautiful! Nice work. 
I see that there's already an open issue on the formatting. Hope we get a response soon.

**Comment by Samoed** [comment]
That's very beautiful!
Here are a few small UI suggestions: maybe move the citation section to the bottom of the page (it could even be collapsible) and switch the order of the table and plot so the table appears at the top after search bar.  What do you think?

**Comment by x-tabdeveloping** [comment]
Hey @Samoed thanks! I have been there :D After deliberation I though having the citation up close to the benchmark description makes more sense since it is more visually linked to the specific benchmark, and also fills up a gap that would otherwise be there. I also prefer having the plot first than the table, since it communicates the same information, while being easier to interpret visually.

I'm open to changing it if enough people think we should rearrange things.

**Review by Muennighoff — APPROVED** [review]
Looks amazing!

**Comment by x-tabdeveloping** [comment]
@Muennighoff @Samoed @isaac-chung @KennethEnevoldsen I would also like to hear your take on whether we should be dark or light theme by default, cause in the case that we want to go dark I can also make the plot with dark background and light text.

**Comment by Samoed** [comment]
I thought gradio uses the system theme by default and I think this is better option

**Comment by x-tabdeveloping** [comment]
Alright, we can stick with the default. It just looks a bit weird to have a light plot against a dark background and vice versa.

**Comment by Muennighoff** [comment]
FYI somehow got the error below when trying to start the LB in a space, but maybe just me?

```
Traceback (most recent call last):
  File "/home/user/app/app.py", line 5, in <module>
    from mteb.leaderboard.app import demo
  File "/usr/local/lib/python3.10/site-packages/mteb/leaderboard/__init__.py", line 3, in <module>
    from mteb.leaderboard.app import demo
  File "/usr/local/lib/python3.10/site-packages/mteb/leaderboard/app.py", line 79, in <module>
    summary_table, per_task_table = scores_to_tables(default_scores)
  File "/usr/local/lib/python3.10/site-packages/mteb/leaderboard/table.py", line 138, in scores_to_tables
    model_metas.map(lambda m: format_n_parameters(m.n_parameters)),
  File "/usr/local/lib/python3.10/site-packages/pandas/core/series.py", line 4700, in map
    new_values = self._map_values(arg, na_action=na_action)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/base.py", line 921, in _map_values
    return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/algorithms.py", line 1743, in map_array
    return lib.map_infer(values, mapper, convert=convert)
  File "lib.pyx", line 2972, in pandas._libs.lib.map_infer
  File "/usr/local/lib/python3.10/site-packages/mteb/leaderboard/table.py", line 138, in <lambda>
    model_metas.map(lambda m: format_n_parameters(m.n_parameters)),
  File "/usr/local/lib/python3.10/site-packages/mteb/leaderboard/table.py", line 36, in format_n_parameters
    n_zeros = math.log10(n_million)
ValueError: math domain error
```

**Comment by x-tabdeveloping** [comment]
hmm strange enough. Maybe some model had model size -1 or None? Can you make an issue on this? @Muennighoff

**Comment by x-tabdeveloping** [comment]
Nvm I got this, will fix in next PR

**Pull request merged**
