### PR TITLE
Added contruction of MTEB(eng, v2) and its lite version

### PR DESCRIPTION
**Pull request by KennethEnevoldsen**
Added task for the EU benchmark for MMTEB. 

- The approach is outlines in the notebook, but mainly follows the approach:
  - select EU tasks
  - remove irrelevant tasks (no license, low quality, code, african etc.)
  - Apply iterative task selection removing the most predictable task (under some conditions, see notebook)
  - Based on the selected task refine the filtering until satisfied

This still needs some review, but generally I think it is close to being finalized. Let me know what you think, I would especially like your opinion on the datasets for languages that you speak.

Note: many of the changes are updates to metadata. This is simply to determine the quality of some of the datasets.

(see also #361 )

### CODE REVIEW

**Review by Muennighoff — COMMENTED** [review]
Nice though I think maybe for doing a new core english benchmark  i.e. mtebv2, we should rather start out with all english benchmarks not the original 56? E.g. something like

1. Look at all English tasks in the codebase
2. Filter for some measure of quality i.e. we only want the best
3. Filter for some measure of diversity (similar to what you did here I think)
4. Filter for some measure of redundancy (similar to what you did here I think)
5. Make them not too expensive to run / have a lite version

**Comment by Muennighoff** [comment]
Curious also what @orionw thinks!

**Comment by orionw** [comment]
I like the approach in the notebook, looks good overall.  I also like that it has the human influence and isn't entirely model driven, I think we have some extra knowledge about quality and such that is hard to fit into the model.

Agree with both of you that for a v2 version we should probably select and then prune back via some of these methods (which is somewhat similar to what we're doing now).

**Comment by KennethEnevoldsen** [comment]
I have now reformulated it to be MTEB lite only - I will set this to merge (to avoid conflict), but I knowing that we still have tasks to add.

**Pull request merged**
