### PR TITLE
add prompt retrieval

### PR DESCRIPTION
**Pull request by hongjin-su**
Add the prompt retrieval for embedding model evaluation.

### CODE REVIEW

**Comment by Muennighoff** [comment]
This is cool! But I think we should integrate it with the existing MTEB interface or does that not make any sense?

cc'ing @dipam7 @KennethEnevoldsen from the issue

**Comment by Muennighoff** [comment]
Here's a great example of a successful integration: https://github.com/embeddings-benchmark/mteb/pull/408
Tagging @orionw here in case he has ideas 😊

**Comment by KennethEnevoldsen** [comment]
Thanks for this PR @hongjin-su, completely agree with @Muennighoff that we would love to integrate this with the existing code-base.

**Comment by KennethEnevoldsen** [comment]
@hongjin-su seems like this PR has gone stale. I will close it for now, but do feel free to re-open it.

**Pull request closed without merging**
